#!/bin/bash
# --------------------------------------------
# Thumbnailer for Graphviz .DOT files
#
# Procedure :
#   http://bernaerts.dyndns.org/linux/76-gnome/333-gnome-shell-graphviz-viewer-thumbnailer
# Depends on :
#   * convert (imagemagick package)
#   * dot (graphviz package)
# Revision history :
#   04/08/2013, V1.0 - Creation by N. Bernaerts
#   25/04/2015, V1.1 - Convert to bash
# -------------------------------------------

# check tools availability
command -v dot >/dev/null 2>&1 || exit 1
command -v convert >/dev/null 2>&1 || exit 1

# get parameters
INPUT="$1"
OUTPUT="$2"
HEIGHT=$3

# go to graphviz DOT file directory
cd $(dirname "${INPUT}")

# generation
dot -Tpng "${INPUT}" | convert -resize x${HEIGHT} - "${OUTPUT}"
