#!/bin/sh
# ---------------------------------------------------
# Thumbnailer for LibreOffice & OpenOffice documents
#
# Procedure :
#   http://bernaerts.dyndns.org/linux/76-gnome/285-gnome-shell-generate-libreoffice-thumbnail-nautilus
# Depends on :
#   * unzip
#   * composite (imagemagick package)
#   * gvfs-copy (gvfs-bin package)
# Parameters :
#   $1 - URI of office file
#   $2 - full path of generated thumbnail
#   $3 - height of thumbnail in pixels
# Revision history :
# 04/08/2013, V1.0 - Creation by N. Bernaerts
# 15/11/2014, V2.0 - Use URI to handle network shares
# ---------------------------------------------------

# check tools availability
command -v gvfs-copy >/dev/null 2>&1 || exit 1
command -v unzip >/dev/null 2>&1 || exit 1
command -v composite >/dev/null 2>&1 || exit 1

# path where to get icons used for generation
ICONPATH="/usr/local/sbin/lo-thumbnailer-icons"

# get parameters
FILE_URI=$1
FILE_THUMB=$2
HEIGHT=$3

# get filename extension
FILE_EXT=$(echo "$FILE_URI" | sed 's/^.*\.\(.*\)/\1/')

# generate temporary local filename
TMP_FILE=$(mktemp -t XXXXXXXX.${FILE_EXT})

# copy input file to temporary local file
gvfs-copy "${FILE_URI}" "${TMP_FILE}"

# get the file mime type (application/vnd.oasis.opendocument...)
MIMETYPE=$(mimetype -b "${TMP_FILE}")

# get document type (text, spreadsheet, graphics or presentation)
DOCTYPE=$(echo "${MIMETYPE}" | sed 's/.*: //' | sed 's/^.*opendocument.\([^-]*\).*/\1/')

# generate thumbnail according to document type
unzip -p "${TMP_FILE}" Thumbnails/thumbnail.png | composite -gravity center \( -resize x244 - \) ${ICONPATH}/lo-${DOCTYPE}.png ${ICONPATH}/lo-mask.png \( -resize x${HEIGHT} \) "${FILE_THUMB}"

# remove temporary local file
rm ${TMP_FILE}
