#!/bin/sh
# -------------------------------------------------------
#  LUbuntu 14.04 LTS Post-installation script
#
#  This script will run some commands as sudo
# 
#  25/05/2014, V1.0 - Creation by N. Bernaerts
#  10/06/2014, V1.1 - Update
#  30/08/2014, V1.2 - Add LibreOffice and GIMP PPA
#  09/09/2014, V1.3 - Add YouTube-dl & ClipGrab
# -------------------------------------------------------

# ---------------------------------------------------
# ------------- User defined variable ---------------
# ---------------------------------------------------

# define where screenshot are saved
SCREENSHOT_DIR="$HOME/Images"

# define remote support address (for gitso)
SUPPORT_SITE="bernaerts-nicolas.dyndns.org"

# ---------------------------------------------------
# ------------ Architecture detection ---------------
# ---------------------------------------------------

RESULT=`uname -a | grep x86_64`
[ "$RESULT" != "" ] && ARCHI="amd64" || ARCHI="i386"
[ "$ARCHI" = "amd64" ] && X86ARCHI="64" || X86ARCHI="32"

# ---------------------------------------------------
# --------------- Full System Update ----------------
# ---------------------------------------------------

sudo add-apt-repository -y ppa:lubuntu-dev/staging
sudo apt-get update
sudo apt-get -y dist-upgrade

# ---------------------------------------------------
# ---------------- System Utilities -----------------
# ---------------------------------------------------

# system extension really needed
sudo apt-get -y install linux-firmware-nonfree xbacklight preload ppa-purge libnotify-bin

# dual display management
sudo apt-get -y install arandr

# trackpad and mouse management
sudo apt-get -y install gpointing-device-settings

# filesystem clients 
sudo apt-get -y install cifs-utils autofs

# compression tools
sudo apt-get -y install p7zip-full rar unrar unzip

# ---------------------------------------------------
# --------------- misc Desktop Tools ----------------
# ---------------------------------------------------

# keepassx : electronic wallet
sudo apt-get -y install keepassx

# PDF editor
wget http://code-industry.net/public/master-pdf-editor_1.9.25_${ARCHI}.deb
sudo gdebi --n master-pdf-editor_1.9.25_*.deb

# ---------------------------------------------------
# ------------------- LibreOffice ------------------
# ---------------------------------------------------

# declare 4.3 PPA & install libreoffice
sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-3
sudo apt-get update
sudo apt-get -y install libreoffice libreoffice-gtk libreoffice-style-sifr

# default file association
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text application/msword
xdg-mime default libreoffice-calc.desktop application/vnd.oasis.opendocument.spreadsheet application/vnd.ms-excel

# ---------------------------------------------------
# ------------------ Graphical Apps -----------------
# ---------------------------------------------------

# misc graphical apps
sudo apt-get -y install exiv2 gcolor2 imagemagick hugin 

# declare 4.3 PPA & install gimp
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo apt-get update
sudo apt-get -y install gimp gimp-plugin-registry

# ---------------------------------------------------
# ----------- Multimedia Codecs & Flash -------------
# ---------------------------------------------------

# auto-accept mscorefonts eula
sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"

# codecs & flash
sudo apt-get --yes --force-yes install lubuntu-restricted-extras x264

# CSS DVD decryption
sudo sh /usr/share/doc/libdvdread4/install-css.sh

# ---------------------------------------------------
# ------------------ Audio tools --------------------
# ---------------------------------------------------

# misc tools
sudo apt-get -y install pavucontrol soundconverter

# mp3 tools
sudo apt-get -y install easymp3gain-gtk easytag id3v2 lame  mp3gain

# ---------------------------------------------------
# ------------------ Video tools --------------------
# ---------------------------------------------------

# video tools
sudo apt-get -y install libav-tools avidemux mkvtoolnix-gui handbrake

# video editor
sudo apt-get -y install openshot

# vlc and declare it as replacement for gnome player 
sudo apt-get -y install vlc
sudo sed -i 's/totem/vlc/g' /usr/share/applications/defaults.list

# ---------------------------------------------------
# ---------------- Internet tools -------------------
# ---------------------------------------------------

# thunderbird
sudo apt-get -y install thunderbird thunderbird-locale-fr thunderbird-gnome-support

# chromium & filezilla
sudo apt-get -y install chromium-bsu filezilla

# Firefox : H264 support
sudo add-apt-repository -y ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get -y install gstreamer0.10-ffmpeg

# Firefox : Hangout plugin
wget https://dl.google.com/linux/direct/google-talkplugin_current_${ARCHI}.deb
sudo gdebi --n google-talkplugin_current_*.deb

# youtube-dl & gui
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install youtube-dl youtube-dlg

# clipgrab (get latest version from homepage)
wget -O clipgrab.htm http://clipgrab.org/
ARCHIVE=`cat clipgrab.htm | grep "tar.gz" | sed 's/^.*=.\(.*\).>/\1/'`
wget -O clipgrab.tar.gz "$ARCHIVE"
tar -xzf clipgrab.tar.gz
sudo mv ./clipgrab*/clipgrab*/clipgrab*_x86_$X86ARCHI /usr/local/bin/clipgrab
sudo chmod +x /usr/local/bin/clipgrab
rm -R clipgrab*

# ---------------------------------------------------
# -------------- Remote assistance ------------------
# ---------------------------------------------------

# gitso
wget http://gitso.googlecode.com/files/gitso_0.6.2_all.deb
sudo gdebi --n gitso_0.6.2_all.deb

# include remote assistance site in launcher
cp /usr/share/applications/gitso.desktop $HOME/.local/share/applications/gitso.desktop
sed -i "/Exec=gitso/c\Exec=gitso --connect $SUPPORT_SITE" $HOME/.local/share/applications/gitso.desktop

# ---------------------------------------------------
# ------------------ Android tools ------------------
# ---------------------------------------------------

# adb and fastboot
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install android-tools-adb android-tools-fastboot

# yad editor (from same PPA)
sudo apt-get -y install yad

# ---------------------------------------------------
# ----------------- Thumbnailers --------------------
# ---------------------------------------------------

# APK thumbnailer
sudo apt-get -y install libstdc++6:i386 lib32z1 lib32ncurses5 lib32bz2-1.0
sudo wget -O /usr/local/sbin/aapt-thumbnailer http://bernaerts.dyndns.org/download/gnome/apk/aapt-thumbnailer
sudo wget -O /usr/local/sbin/apk-thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/apk-thumbnailer/apk-thumbnailer
sudo chmod +rx /usr/local/sbin/apk-thumbnailer /usr/local/sbin/aapt-thumbnailer
sudo wget -O /usr/share/thumbnailers/apk.thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/apk-thumbnailer/apk.thumbnailer 

# LibreOffice thumbnailer
wget http://bernaerts.dyndns.org/download/gnome/libreoffice/lo-thumbnailer-icons.zip
sudo unzip -d /usr/local/sbin lo-thumbnailer-icons.zip
rm lo-thumbnailer-icons.zip
sudo wget -O /usr/local/sbin/lo-thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/libreoffice-thumbnailer/lo-thumbnailer
sudo chmod +rx /usr/local/sbin/lo-thumbnailer
sudo wget -O /usr/share/thumbnailers/lo.thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/libreoffice-thumbnailer/lo.thumbnailer

# ---------------------------------------------------
# ------------------ Package cleanup ----------------
# ---------------------------------------------------

sudo apt-get -y autoremove
sudo apt-get -y autoclean

# ---------------------------------------------------
# --------------- Lubuntu 14.04 tweaks --------------
# ---------------------------------------------------
 
# start network applet (Lubuntu 14.04 bug, corrected in 14.04.1)
#echo "nm-applet" >> $HOME/.config/lxsession/Lubuntu/autostart
 
# Set double click time to 400ms (instead of 200ms)
sed -i 's,.*doubleClickTime.*,<doubleClickTime>400<\/doubleClickTime>,' $HOME/.config/openbox/lubuntu-rc.xml
 
# set target directory for screenshots
sed -i 's,.*<command>lxsession-default screenshot<\/command>.*,      <command>scrot -e "mv $f '"$SCREENSHOT_DIR"'"<\/command>,' $HOME/.config/openbox/lubuntu-rc.xml
sed -i 's,.*<command>lxsession-default screenshot window<\/command>.*,      <command>scrot --focused -e "mv $f '"$SCREENSHOT_DIR"'"<\/command>,' $HOME/.config/openbox/lubuntu-rc.xml

# Declare shortcuts to switch single / dual display
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/lubuntu/dual-display/declare-dualdisplay
chmod +x ./declare-dualdisplay
sudo ./declare-dualdisplay
