#!/bin/sh
# -------------------------------------------------------
#  LUbuntu 14.04 LTS Post-installation script
#
#  This script will run some commands as sudo
# 
#  25/05/2014, V1.0 - Creation by N. Bernaerts
#  10/06/2014, V1.1 - Update
# -------------------------------------------------------

# detect current architecture (i386 or amd64)
RESULT=`uname -a | grep x86_64`
[ "$RESULT" != "" ] && ARCHI="amd64" || ARCHI="i386"

# ---------------------------------------------------
# --------------- Full System Update ----------------
# ---------------------------------------------------

sudo add-apt-repository -y ppa:lubuntu-dev/staging
sudo apt-get update
sudo apt-get -y dist-upgrade

# ---------------------------------------------------
# ---------------- System Utilities -----------------
# ---------------------------------------------------

# system extension really needed
sudo apt-get -y install linux-firmware-nonfree xbacklight preload ppa-purge libnotify-bin

# filesystem clients 
sudo apt-get -y install cifs-utils autofs

# compression tools
sudo apt-get -y install p7zip-full rar unrar unzip

# ---------------------------------------------------
# --------------- misc Desktop Tools ----------------
# ---------------------------------------------------

# keepassx : electronic wallet
sudo apt-get -y install keepassx

# PDF editor
wget http://code-industry.net/public/master-pdf-editor_1.9.25_${ARCHI}.deb
sudo gdebi --n master-pdf-editor_1.9.25_*.deb

# ---------------------------------------------------
# ------------------- LibreOffice ------------------
# ---------------------------------------------------

# application
sudo apt-get -y install libreoffice libreoffice-gtk

# default file association
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text application/msword
xdg-mime default libreoffice-calc.desktop application/vnd.oasis.opendocument.spreadsheet application/vnd.ms-excel

# ---------------------------------------------------
# ------------------ Graphical Apps -----------------
# ---------------------------------------------------

# misc graphical apps
sudo apt-get -y install exiv2 gcolor2 imagemagick hugin 

# gimp
sudo apt-get -y install gimp gimp-plugin-registry

# ---------------------------------------------------
# ----------- Multimedia Codecs & Flash -------------
# ---------------------------------------------------

# auto-accept mscorefonts eula
sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"

# codecs & flash
sudo apt-get --yes --force-yes install lubuntu-restricted-extras x264

# CSS DVD decryption
sudo sh /usr/share/doc/libdvdread4/install-css.sh

# ---------------------------------------------------
# ------------------ Audio tools --------------------
# ---------------------------------------------------

# misc tools
sudo apt-get -y install pavucontrol soundconverter

# mp3 tools
sudo apt-get -y install easymp3gain-gtk easytag id3v2 lame  mp3gain

# ---------------------------------------------------
# ------------------ Video tools --------------------
# ---------------------------------------------------

# video tools
sudo apt-get -y install libav-tools avidemux mkvtoolnix-gui handbrake

# video editor
sudo apt-get -y install openshot

# ---------------------------------------------------
# ---------------- Internet tools -------------------
# ---------------------------------------------------

# thunderbird
sudo apt-get -y install thunderbird thunderbird-locale-fr thunderbird-gnome-support

# chromium & filezilla
sudo apt-get -y install chromium-bsu filezilla

# remote assistance
wget http://gitso.googlecode.com/files/gitso_0.6.2_all.deb
sudo gdebi --n gitso_0.6.2_all.deb

# Firefox : H264 support
sudo add-apt-repository -y ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get -y install gstreamer0.10-ffmpeg

# Firefox : Hangout plugin
wget https://dl.google.com/linux/direct/google-talkplugin_current_${ARCHI}.deb
sudo gdebi --n google-talkplugin_current_*.deb

# ---------------------------------------------------
# ------------------ Android tools ------------------
# ---------------------------------------------------

# adb and fastboot
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install android-tools-adb android-tools-fastboot

# yad editor (from same PPA)
sudo apt-get -y install yad

# ---------------------------------------------------
# ----------------- Thumbnailers --------------------
# ---------------------------------------------------

# APK thumbnailer (to be tested)
sudo apt-get -y install libstdc++6:i386 lib32z1 lib32ncurses5 lib32bz2-1.0
wget http://bernaerts.dyndns.org/download/gnome/apk/apk-thumbnailer.zip
sudo unzip -d /usr/local/sbin apk-thumbnailer.zip && rm apk-thumbnailer.zip
sudo chmod +rx /usr/local/sbin/apk-thumbnailer /usr/local/sbin/aapt-thumbnailer
sudo wget -O /usr/share/thumbnailers/apk.thumbnailer http://bernaerts.dyndns.org/download/gnome/apk/apk.thumbnailer

# LibreOffice thumbnailer
wget https://github.com/NicolasBernaerts/libreoffice-thumbnailer/raw/master/lo-thumbnailer-icons.zip 
sudo unzip -d /usr/local/sbin lo-thumbnailer-icons.zip
rm lo-thumbnailer-icons.zip
sudo wget -O /usr/local/sbin/lo-thumbnailer https://github.com/NicolasBernaerts/libreoffice-thumbnailer/raw/master/lo-thumbnailer
sudo chmod +rx /usr/local/sbin/lo-thumbnailer
sudo wget -O /usr/share/thumbnailers/lo.thumbnailer https://github.com/NicolasBernaerts/libreoffice-thumbnailer/raw/master/lo.thumbnailer

# ---------------------------------------------------
# --------------------- Cleanup ---------------------
# ---------------------------------------------------

sudo apt-get -y autoremove
sudo apt-get -y autoclean
