#!/usr/bin/env bash
# -----------------------------------------------------
# Utility to Scan documents from HP AIO printer/scanner
#
# Depends on :
#  * scanimage
#  * imagemagick (for mogrify)
#  * ghostscript (for gs)
#  * yad
#
# Revision history :
#  08/02/2013, V1.0 - Creation by N. Bernaerts
#  27/09/2014, V2.0 - Rework & multi scanner support
#  24/01/2015, V2.1 - Check tools availability
#  26/02/2016, V2.2 - Move config to ~/.config and add auto adjust level
#  28/02/2016, V2.3 - Select page size and generate multi-pages PDF (thanks to Kevin McArdle idea)
#  05/06/2017, V2.4 - Code cleanup
#  06/06/2020, V2.5 - Conversion of lists to arrays
# ----------------------------------------------------

# check tools availability
command -v scanimage >/dev/null 2>&1 || { zenity --error --text="Please install scanimage"; exit 1; }
command -v mogrify >/dev/null 2>&1 || { zenity --error --text="Please install mogrify [imagemagick package]"; exit 1; }
command -v gs >/dev/null 2>&1 || { zenity --error --text="Please install gs [ghostscript package]"; exit 1; }
command -v yad >/dev/null 2>&1 || { zenity --error --text="Please install yad"; exit 1; }

# define and check configuration file
CONF_FILE="$HOME/.config/scan2folder.conf"
[ -f "${CONF_FILE}" ] || { zenity --error --text="Please create and configure ${CONF_FILE}"; exit 1; }

# generate temporary files and directory
TMP_DIR=$(mktemp -t -d "scan-XXXXXXXX")
TMP_LIST="${TMP_DIR}/list.txt"
TMP_CONF="${TMP_DIR}/file.conf"

# default dialog box width
DLG_WIDTH=600

# set choice possibilities
CHOICE_SCAN=0
CHOICE_EXIT=1
CHOICE_SAVE=2
CHOICE_DEVICE=3
CHOICE_PARAM=4

# ------------------------
#      Load config
# ------------------------

SCAN_NAME=$(cat "${CONF_FILE}" | grep "scanner-name=" | cut -d"=" -f2-)
SCAN_DEVICE=$(cat "${CONF_FILE}" | grep "scanner-device=" | cut -d"=" -f2-)

ARR_FORMAT=( $(cat "${CONF_FILE}" | grep "list-format=" | cut -d"=" -f2- | tr ',' '\n') )
ARR_PAGE=( $(cat "${CONF_FILE}" | grep "list-page=" | cut -d"=" -f2- | tr -d ' ' | tr ',' '\n') )
ARR_DPI=( $(cat "${CONF_FILE}" | grep "list-dpi=" | cut -d"=" -f2- | tr ',' '\n') )
ARR_MODE=( $(cat "${CONF_FILE}" | grep "list-mode=" | cut -d"=" -f2- | tr ',' '\n') )
ARR_SOURCE=( $(cat "${CONF_FILE}" | grep "list-source=" | cut -d"=" -f2- | tr ',' '\n') )

PAGE=$(cat "${CONF_FILE}" | grep "default-page=" | cut -d"=" -f2)
DPI=$(cat "${CONF_FILE}" | grep "default-dpi=" | cut -d"=" -f2)
MODE=$(cat "${CONF_FILE}" | grep "default-mode=" | cut -d"=" -f2)
SOURCE=$(cat "${CONF_FILE}" | grep "default-source=" | cut -d"=" -f2)
FORMAT=$(cat "${CONF_FILE}" | grep "default-format=" | cut -d"=" -f2)
DIRECTORY=$(cat "${CONF_FILE}" | grep "default-dir=" | cut -d"=" -f2-)

# if no scanner selected, force device scanning
[ "${SCAN_DEVICE}" = "" ] && CHOICE="${CHOICE_DEVICE}" || CHOICE="${CHOICE_PARAM}"

# ------------------------
#         Main loop
# ------------------------

while [ "${CHOICE}" != "${CHOICE_EXIT}" ]
do case ${CHOICE} in

  # ---------------------
  #     Scan pages
  # ---------------------
  ${CHOICE_SCAN})
  
    (
    # beginning
    echo 0
  
    # generate timestamped filename
    FILE=$(date '+Scan-%Y%b%d-%Ih%Mm%Ss')

    # display scan message
    echo "# Scanning document from ${SOURCE} (${DPI} dpi) ..."
    
    # parameters
    ARR_PARAM=( "--device-name=${SCAN_DEVICE}" "--format=pnm"  "--batch=${TMP_DIR}/${FILE}-%d.pnm" )
    ARR_PARAM=( "${ARR_PARAM[@]}" "--mode=${MODE}" "--resolution=${DPI}" "--source" "${SOURCE}" )
    [ "${SOURCE}" = "Flatbed" ] && ARR_PARAM=( "${ARR_PARAM[@]}" "--batch-count" "1" )

    # scan image with needed resolution
    NUMBER=$(scanimage "${ARR_PARAM[@]}" 2>&1 | grep "terminated" | cut -d',' -f2 | xargs | cut -d' ' -f1)

    # display conversion message
    echo "# Converting ${NUMBER} document(s) ..."

    # calculate default size according to page type
    WIDTH_MM=$(echo ${ARR_PAGE[@]} | tr ' ' '\n' | grep "^${PAGE}" | cut -d'(' -f2 | cut -d'x' -f1)
    HEIGHT_MM=$(echo ${ARR_PAGE[@]} | tr ' ' '\n' | grep "^${PAGE}" | cut -d'x' -f2 | cut -d')' -f1)
    WIDTH_PIX=$((10*${WIDTH_MM}*${DPI}/254))
    HEIGHT_PIX=$((10*${HEIGHT_MM}*${DPI}/254))

    # auto adjust levels and crop picture to target page size
    mogrify -crop "${WIDTH_PIX}x${HEIGHT_PIX}+0+0" -auto-level ${TMP_DIR}/${FILE}*.pnm

    # convert to proper format
    mogrify -format "${FORMAT}" -page "${PAGE}" ${TMP_DIR}/${FILE}*.pnm
    
    # if needed, merge all scanned documents in a single PDF file
    if [ "${FORMAT}" = "pdf" ]
    then
      # generate array of PDF files
      ARR_PDF=( $(ls ${TMP_DIR}/${FILE}*.pdf) )

      # generate resulting PDF
      gs -q -dNOPAUSE -dBATCH -dSAFER -sPAPERSIZE=${PAGE} -dPDFFitPage -dCompatibilityLevel=1.4 -sDEVICE=pdfwrite "-sOutputFile=${DIRECTORY}/${FILE}.pdf" "${ARR_PDF[@]}"
    else
        # move documents
    	mv ${TMP_DIR}/${FILE}*.${FORMAT} ${DIRECTORY} 
    fi

    # end
    echo 100
    ) | yad --center --width=${DLG_WIDTH} --window-icon="scanner" --image="scanner" --title "Scanning documents ..." --text="" --progress --pulsate --auto-close --no-buttons

    # back to parameter dialog box
    CHOICE="${CHOICE_PARAM}"
    ;;

  # -------------------------
  #     Save parameters
  # -------------------------
  
  ${CHOICE_SAVE})
    # convert arrays to lists
    LIST_FORMAT=$(echo "${ARR_FORMAT[@]}" | xargs | tr ' ' ',')
    LIST_PAGE=$(echo "${ARR_PAGE[@]}" | xargs | tr ' ' ',')
    LIST_DPI=$(echo "${ARR_DPI[@]}" | xargs | tr ' ' ',')
    LIST_MODE=$(echo "${ARR_MODE[@]}" | xargs | tr ' ' ',')
    LIST_SOURCE=$(echo "${ARR_SOURCE[@]}" | xargs | tr ' ' ',')
  
    # save configuration
    echo "[scanner]" > ${CONF_FILE}
    echo "scanner-name=${SCAN_NAME}" >> ${CONF_FILE}
    echo "scanner-device=${SCAN_DEVICE}" >> ${CONF_FILE}

    echo "[list]" >> ${CONF_FILE}
    echo "list-format=${LIST_FORMAT}" >> ${CONF_FILE}
    echo "list-page=${LIST_PAGE}" >> ${CONF_FILE}
    echo "list-dpi=${LIST_DPI}" >> ${CONF_FILE}
    echo "list-mode=${LIST_MODE}" >> ${CONF_FILE}
    echo "list-source=${LIST_SOURCE}" >> ${CONF_FILE}

    echo "[default]" >> ${CONF_FILE}
    echo "default-page=${PAGE}" >> ${CONF_FILE}
    echo "default-dpi=${DPI}" >> ${CONF_FILE}
    echo "default-mode=${MODE}" >> ${CONF_FILE}
    echo "default-source=${SOURCE}" >> ${CONF_FILE}
    echo "default-format=${FORMAT}" >> ${CONF_FILE}
    echo "default-dir=${DIRECTORY}" >> ${CONF_FILE}

    # back to parameter dialog box
    CHOICE=${CHOICE_PARAM}
    ;;

  # ------------------------
  #      Select scanner
  # ------------------------
  
  ${CHOICE_DEVICE})
  
    # list available scanners (remove all spaces and set space as separator)
    (
    echo 0
    scanimage --list-devices > "${TMP_LIST}"
    echo 100
    ) | yad --center --width=${DLG_WIDTH} --window-icon="scanner" --image="scanner" --title "Detecting scanners ..." --text="" --progress --pulsate --auto-close --no-buttons

    # generate scanner list
    LIST_SCANNER=$(cat "${TMP_LIST}" | sed 's/device..\(.*\). is a \(.*\)$/\2|\1/' | tr ' ' '_' | tr '|' ' ' | tr '\n' ' ')

    # display scanner selection dialog
    TITLE="Scanner selection"
    TEXT="Select scanner to use"
    SELECTION=$(yad --center --width=$DLG_WIDTH --height=250 --window-icon="scanner" --image="scanner" \
                    --title="$TITLE" --text="$TEXT" \
                    --list --column="Scanner" --column="Device" --hide-column=2 ${LIST_SCANNER})

    # if needed, update current scanner
    if [ "${SELECTION}" != "" ]
    then
      # retrieve selected scanner
      SCAN_NAME=$(echo "${SELECTION}" | cut -d'|' -f1 | tr '_' ' ')
      SCAN_DEVICE=$(echo "${SELECTION}" | cut -d'|' -f2)
 
      # get scanner possibilities
      (
      echo 0
      scanimage --help --device "${SCAN_DEVICE}" > "${TMP_CONF}"
      echo 100
      ) | yad --center --width=${DLG_WIDTH} --window-icon="scanner" --image="scanner" --title "Retrieving scanner parameters ..." --text="" --progress --pulsate --auto-close --no-buttons

      # retreive parameters list
      ARR_DPI=( $(cat "${TMP_CONF}" | grep "\-\-resolution" | xargs | cut -d' ' -f2 | sed 's/[^0-9|]*//g' | tr '|' '\n') )
      ARR_MODE=( $(cat "${TMP_CONF}" | grep "\-\-mode" | xargs | cut -d' ' -f2 | tr '|' '\n') )
      ARR_SOURCE=( $(cat "${TMP_CONF}" | grep "\-\-source" | xargs | cut -d' ' -f2 | tr '|' '\n') )

      # retreive default values
      DPI=$(cat "${TMP_CONF}" | grep "\-\-resolution" | cut -d'[' -f2 | cut -d']' -f1)
      MODE=$(cat "${TMP_CONF}" | grep "\-\-mode" | cut -d'[' -f2 | cut -d']' -f1)
      SOURCE=$(cat "${TMP_CONF}" | grep "\-\-source" | cut -d'[' -f2 | cut -d']' -f1)
    fi

    # back to parameter dialog box
    CHOICE="${CHOICE_PARAM}"
    ;;

  # -------------------------------
  #     Select scan parameters
  # -------------------------------
  
  ${CHOICE_PARAM})
  
    # prepare dialog box combo lists
    #   -> place default choice as top of the list
    DLG_DPI=$(echo "${DPI},$(echo "${ARR_DPI[@]}" | tr ' ' '\n' | grep -v "^${DPI}$" | xargs | tr ' ' ',')")
    DLG_MODE=$(echo "${MODE},$(echo "${ARR_MODE[@]}" | tr ' ' '\n' | grep -v "^${MODE}$" | xargs | tr ' ' ',')")
    DLG_SOURCE=$(echo "${SOURCE},$(echo "${ARR_SOURCE[@]}" | tr ' ' '\n' | grep -v "^${SOURCE}$" | xargs | tr ' ' ',')")
    DLG_FORMAT=$(echo "${FORMAT},$(echo "${ARR_FORMAT[@]}" | tr ' ' '\n' | grep -v "^${FORMAT}$" | xargs | tr ' ' ',')")
    DLG_PAGE=$(echo "${PAGE},$(echo "${ARR_PAGE[@]}" | tr ' ' '\n' | grep -v "^${PAGE}" | cut -d'(' -f1 | xargs | tr ' ' ',')")

    # Scan parameter selection dialog
    TITLE="Scanning parameters"
    TEXT="Select parameters for the scan job :"
    SELECTION=$(yad --center "--width=${DLG_WIDTH}" "--window-icon=scanner" "--image=scanner" "--title=${TITLE}" "--text=${TEXT}" \
                   "--button=Device:${CHOICE_DEVICE}" "--button=Save:${CHOICE_SAVE}" "--button=Close:${CHOICE_EXIT}" "--button=Scan:${CHOICE_SCAN}" \
                   --form --item-separator="," "--field=Scanner:RO" "${SCAN_NAME}" \
                   "--field=Resolution:CB" "${DLG_DPI}" "--field=Mode:CB" "${DLG_MODE}" "--field=Source:CB" "${DLG_SOURCE}" "--field=Format:CB" "${DLG_FORMAT}" \
                   "--field=Page size:CB" "${DLG_PAGE}" "--field=Location:DIR" "${DIRECTORY}")
    CHOICE=$?

    # if needed, update parameters from dialog box selection
    if [ "${SELECTION}" != "" ]
    then
      DPI=$(echo "${SELECTION}" | cut -d"|" -f2)
      MODE=$(echo "${SELECTION}" | cut -d"|" -f3)
      SOURCE=$(echo "${SELECTION}" | cut -d"|" -f4)
      FORMAT=$(echo "${SELECTION}" | cut -d"|" -f5)
      PAGE=$(echo "${SELECTION}" | cut -d"|" -f6)
      DIRECTORY=$(echo "${SELECTION}" | cut -d"|" -f7)
    fi
    ;;

  # ---------------------------
  #     Unexpected choice
  # ---------------------------
  *)
    # by default, exit
    CHOICE="${CHOICE_EXIT}"
    ;;
  esac
done

# remove temporary directory
rm -r "${TMP_DIR}"

