#!/bin/bash
# ---------------------------------------------------------------------
#  Script to backup/restore current user folders and application data
#  on any removable media during computer complete reinstallation
#
#  Backup  :  ./data-transfer --backup /full/path/to/media ...
#  Restore :  ./data-transfer --restore /full/path/to/media ...
#
#  All backup files will be stored under /full/path/to/media
#
#  Revision history :
#   10/06/2016, V1.0 - Creation by N. Bernaerts
#   15/08/2016, V1.1 - Add target directory
# ---------------------------------------------------------------------

# check xdg-user-dir
command -v xdg-user-dir >/dev/null 2>&1 || { zenity --error --text="Please install xdg-user-dir utility"; exit 1; }

# set environments to backup/restore
#   ApplicationOrFolderName|BackupMode (tar:compress to tar.gz / dir:copy to directory)|DataPath
CFG_DESKTOP="desktop|dir|$(xdg-user-dir DESKTOP)"
CFG_DOCUMENTS="documents|tar|$(xdg-user-dir DOCUMENTS)"
CFG_MUSIC="music|dir|$(xdg-user-dir MUSIC)"
CFG_PICTURES="pictures|dir|$(xdg-user-dir PICTURES)"
CFG_VIDEOS="videos|dir|$(xdg-user-dir VIDEOS)"
CFG_SSH="ssh|tar|$HOME/.ssh"
CFG_FIREFOX="firefox|tar|$HOME/.mozilla/firefox"
CFG_THUNDERBIRD="thunderbird|tar|$HOME/.thunderbird"
CFG_TELEGRAM="telegram|tar|$HOME/.TelegramDesktop"
CFG_WHATSIE="whatsie|tar|$HOME/.config/Whatsie"
CFG_SKYPE="skype|tar|$HOME/.Skype"

# by default, backup mode
RUN_MODE="backup"

# help message if no parameter
if [ ${#} -eq 0 ];
then
    echo "Script to backup/restore user data."
    echo "General parameters :"
    echo "  --backup <path>     Backup files to specified path"
    echo "  --restore <path>    Restore files to specified path"
    echo "Folders content :"
    echo "  --desktop           Desktop folder"
    echo "  --documents         Documents folder"
    echo "  --music             Music folder"
    echo "  --pictures          Pictures folder"
    echo "  --videos            Videos folder"
    echo "  --all-folders       All previous folders"
    echo "Application data :"
    echo "  --ssh               OpenSSH data"
    echo "  --firefox           Firefox data"
    echo "  --thunderbird       Thunderbird data"
    echo "  --telegram          Telegram data"
    echo "  --whatsie           WhatsIe data"
    echo "  --skype             Skype data"
    echo "  --all-apps          All previous applications data"
    exit 1
fi

# iterate thru parameters
while test ${#} -gt 0
do
  case $1 in
    --backup) shift; BACKUP_DIR="$1"; RUN_MODE="backup"; shift; ;;
    --restore) shift; BACKUP_DIR="$1"; RUN_MODE="restore"; shift; ;;
    --desktop) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_DESKTOP}" ); shift; ;;
    --documents) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_DOCUMENTS}" ); shift; ;;
    --music) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_MUSIC}" ); shift; ;;
    --pictures) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_PICTURES}" ); shift; ;;
    --videos) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_VIDEOS}" ); shift; ;;
    --all-folders) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_DESKTOP}" "${CFG_DOCUMENTS}" "${CFG_MUSIC}" "${CFG_PICTURES}" "${CFG_VIDEOS}" ); shift; ;;
    --ssh) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_SSH}" ); shift; ;;
    --firefox) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_FIREFOX}" ); shift; ;;
    --thunderbird) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_THUNDERBIRD}" ); shift; ;;
    --telegram) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_TELEGRAM}" ); shift; ;;
    --whatsie) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_WHATSIE}" ); shift; ;;
    --skype) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_SKYPE}" ); shift; ;;
    --all-apps) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_SSH}" "${CFG_FIREFOX}" "${CFG_THUNDERBIRD}" "${CFG_TELEGRAM}" "${CFG_WHATSIE}" "${CFG_SKYPE}" ); shift; ;;
    *) shift; ;;
  esac
done

# test existence of backup directory
[ ! -d ${BACKUP_DIR} ] && { echo "Directory ${BACKUP_DIR} doesn't exist."; exit; }

# loop thru applications
for APP_TODO in "${ARR_TODO[@]}"
do
  # get data
  APP_NAME=$(echo ${APP_TODO} | cut -d'|' -f1)
  APP_MODE=$(echo ${APP_TODO} | cut -d'|' -f2)
  APP_PATH=$(echo ${APP_TODO} | cut -d'|' -f3)

  # backup mode
  if [ "${RUN_MODE}" = "backup" ];
  then
    # tar.gz mode
    if [ -d "${APP_PATH}" -a "${APP_MODE}" = "tar" ];
    then
      rm --force "${BACKUP_DIR}/${APP_NAME}.tar.gz"
      cd "${APP_PATH}"
      tar -zcvf "${BACKUP_DIR}/${APP_NAME}.tar.gz" *
    fi

    # directory mode
    if [ -d "${APP_PATH}" -a "${APP_MODE}" = "dir" ];
    then
      rmdir --parents "${BACKUP_DIR}/${APP_NAME}"
      mkdir "${BACKUP_DIR}/${APP_NAME}"
      cp --recursive --verbose ${APP_PATH}/* "${BACKUP_DIR}/${APP_NAME}"
    fi
  fi

  # restore mode
  if [ "${RUN_MODE}" = "restore" ];
  then
    # tar.gz mode
    if [ -f "${BACKUP_DIR}/${APP_NAME}.tar.gz" -a "${APP_MODE}" = "tar" ];
    then
      [ -d "${APP_PATH}" ] || mkdir --parents "${APP_PATH}"
      rm --force --recursive ${APP_PATH}/*
      cd "${APP_PATH}"
      tar -zxvf "${BACKUP_DIR}/${APP_NAME}.tar.gz"
    fi

    # directory mode
    if [ -d "${BACKUP_DIR}/${APP_NAME}" -a "${APP_MODE}" = "dir" ];
    then
      [ -d "${APP_PATH}" ] || mkdir --parents "${APP_PATH}"
      rm --recursive --force ${APP_PATH}/*
      cp --recursive --verbose ${BACKUP_DIR}/${APP_NAME}/* "${APP_PATH}"
    fi
  fi
done
