#!/bin/bash
# ---------------------------------------------------
# Thumbnailer for GIMP XCF files
#
# Procedure :
#   http://bernaerts.dyndns.org/linux/76-gnome/xxx
# Depends on :
#   * xcf2pnm (xcftools package)
#   * pnmscalefixed and pnmtopng (netpbm package)
# Parameters :
#   $1 - path of XCF file
#   $2 - path of generated thumbnail
#   $3 - height of thumbnail in pixels
# Revision history :
#   26/11/2014, V1.0 - Creation by N. Bernaerts
#   07/10/2017, V1.1 - Speedup with netpbm tools
#   11/12/2018, V1.2 - Rework for bubblewrap compatibility
# ---------------------------------------------------

# check tools availability 
command -v xcf2pnm >/dev/null 2>&1 || { echo "[error] xcf2pnm missing"; exit 1; }
command -v pnmscalefixed >/dev/null 2>&1 || { echo "[error] pnmscalefixed missing"; exit 1; }
command -v pnmtopng >/dev/null 2>&1 || { echo "[error] pnmtopng missing"; exit 1; }

# get parameters
FILE_LOCAL="$1"
FILE_THUMB="$2"
HEIGHT="$3"

# generate thumbnail
xcf2pnm -c --autocrop "${FILE_LOCAL}" | pnmscalefixed -xysize ${HEIGHT} ${HEIGHT} - | pnmtopng -downscale -compression 0 - > "${FILE_THUMB}"
