#!/bin/bash
# -------------------------------------------------------
# Script to install android tools
#
# 10/05/2016, V1.0 - Migrated from Trusty
# -------------------------------------------------------

# install mtpfs
sudo apt-get -y install mtpfs

# latest versions of adb and fastboot from Google
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/android-tools-install.sh
. ./android-tools-install.sh
rm android-tools-install.sh

# declare complementary devices
sudo wget --header='Accept-Encoding:none' -O /etc/udev/rules.d/51-android.rules https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/51-android.rules
sudo chmod a+r /etc/udev/rules.d/51-android.rules
sudo wget --header='Accept-Encoding:none' -O /etc/udev/rules.d/69-mtp.rules https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/69-mtp.rules
sudo chmod a+r /etc/udev/rules.d/69-mtp.rules
mkdir --parent ~/.android
wget --header='Accept-Encoding:none' -O ~/.android/adb_usb.ini https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/adb_usb.ini

# APK thumbnailer
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/apk/apk-thumbnailer-install.sh
. ./apk-thumbnailer-install.sh
rm apk-thumbnailer-install.sh

# file manager APK extensions
mkdir --parents $HOME/.local/share/nautilus-python/extensions
wget --header='Accept-Encoding:none' -O $HOME/.local/share/nautilus-python/extensions/apk-columns.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/apk-columns.py
wget --header='Accept-Encoding:none' -O $HOME/.local/share/nautilus-python/extensions/apk-properties.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/apk-properties.py

# android screenshot utility
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/android-screenshot-install.sh
. ./android-screenshot-install.sh
rm android-screenshot-install.sh

# QtABD
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/qtadb-install.sh
. ./qtadb-install.sh
rm qtadb-install.sh
