#!/bin/bash
# -------------------------------------------------------
#  Remote assistance installation script
#
#  Uses gitso and teamviewer
#
#  Needs to configure support site
# 
#  15/05/2016, V1.0 - Migrated from Trusty
# -------------------------------------------------------

# define remote support address (for gitso)
SUPPORT_SITE="bernaerts-nicolas.dyndns.org"

# gitso
logger "assistance - gitso"
sudo apt-get -y install gitso
cp /usr/share/applications/gitso.desktop $HOME/.local/share/applications/gitso.desktop
sed -i "/Exec=gitso/c\Exec=gitso --connect $SUPPORT_SITE" $HOME/.local/share/applications/gitso.desktop

# TeamViewer
logger "assistance - TeamViewer"
wget -O teamviewer.deb https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
if [ -f ./teamviewer.deb ]
then
  sudo dpkg -i ./teamviewer.deb
  sudo apt-get -y -f install
  rm ./teamviewer.deb
fi
