#!/bin/bash
# -------------------------------------------------------
#  Remote assistance installation script for Bionic
#
#  Uses gitso and teamviewer
#
#  Needs to configure support site
# 
#  02/06/2018, V1.0 - Migrated from Xenial
# -------------------------------------------------------

# TeamViewer
logger "assistance - TeamViewer"
wget -O teamviewer.deb https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
if [ -f ./teamviewer.deb ]
then
  sudo dpkg -i ./teamviewer.deb
  sudo apt -y -f install
  rm ./teamviewer.deb
fi
