#!/bin/bash
# --------------------------------------------
#
#  Call should be done like :
#   bash /full/path/to/media/data-transfer --parameters
#
#  Revision history :
#   10/06/2016, V1.0 - Creation by N. Bernaerts
# ---------------------------------------------------

# check xdg-user-dir
command -v xdg-user-dir >/dev/null 2>&1 || { zenity --error --text="Please install xdg-user-dir utility"; exit 1; }

# set environments to backup/restore
#   ApplicationOrFolderName|DataPath|BackupMode (tar:compress to tar.gz / dir:copy to directory)
CFG_DESKTOP="desktop|$(xdg-user-dir DESKTOP)|dir"
CFG_DOCUMENTS="documents|$(xdg-user-dir DOCUMENTS)|tar"
CFG_MUSIC="music|$(xdg-user-dir MUSIC)|dir"
CFG_PICTURES="pictures|$(xdg-user-dir PICTURES)|dir"
CFG_VIDEOS="videos|$(xdg-user-dir VIDEOS)|dir"
CFG_SSH="ssh|$HOME/.ssh|tar"
CFG_FIREFOX="firefox|$HOME/.mozilla/firefox|tar"
CFG_THUNDERBIRD="thunderbird|$HOME/.thunderbird|tar"
CFG_TELEGRAM="telegram|$HOME/.TelegramDesktop|tar"
CFG_WHATSIE="whatsie|$HOME/.config/Whatsie|tar"
CFG_SKYPE="skype|$HOME/.Skype|tar"

# by default, backup mode
RUN_MODE="backup"

# help message if no parameter
if [ ${#} -eq 0 ];
then
    echo "Script to backup/restore user data on the media where script runs"
    echo "Parameters are :"
    echo "  --backup         Backup mode"
    echo "  --restore        Restore mode"
    echo "  --desktop        Desktop folder"
    echo "  --documents      Documents folder"
    echo "  --music          Music folder"
    echo "  --pictures       Pictures folder"
    echo "  --videos         Videos folder"
    echo "  --all-folders    All previous folders"
    echo "  --ssh            OpenSSH data"
    echo "  --firefox        Firefox data"
    echo "  --thunderbird    Thunderbird data"
    echo "  --telegram       Telegram data"
    echo "  --whatsie        WhatsIe data"
    echo "  --skype          Skype data"
    echo "  --all-apps       All previous applications data"
    exit 1
fi

# iterate thru parameters
while test ${#} -gt 0
do
  case $1 in
    --backup) RUN_MODE="backup"; shift; ;;
    --restore) RUN_MODE="restore"; shift; ;;
    --desktop) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_DESKTOP}" ); shift; ;;
    --documents) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_DOCUMENTS}" ); shift; ;;
    --music) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_MUSIC}" ); shift; ;;
    --pictures) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_PICTURES}" ); shift; ;;
    --videos) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_VIDEOS}" ); shift; ;;
    --all-folders) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_DESKTOP}" "${CFG_DOCUMENTS}" "${CFG_MUSIC}" "${CFG_PICTURES}" "${CFG_VIDEOS}" ); shift; ;;
    --ssh) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_SSH}" ); shift; ;;
    --firefox) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_FIREFOX}" ); shift; ;;
    --thunderbird) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_THUNDERBIRD}" ); shift; ;;
    --telegram) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_TELEGRAM}" ); shift; ;;
    --whatsie) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_WHATSIE}" ); shift; ;;
    --skype) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_SKYPE}" ); shift; ;;
    --all-apps) ARR_TODO=( "${ARR_TODO[@]}" "${CFG_SSH}" "${CFG_FIREFOX}" "${CFG_THUNDERBIRD}" "${CFG_TELEGRAM}" "${CFG_WHATSIE}" "${CFG_SKYPE}" ); shift; ;;
    *) shift; ;;
  esac
done

# get key path
BACKUP_SCRIPT=$(readlink -f $0)
BACKUP_DIR=$(dirname "${BACKUP_SCRIPT}")

# loop thru applications
for APP_TODO in "${ARR_TODO[@]}"
do
  # get data
  APP_NAME=$(echo ${APP_TODO} | cut -d'|' -f1)
  APP_PATH=$(echo ${APP_TODO} | cut -d'|' -f2)
  APP_MODE=$(echo ${APP_TODO} | cut -d'|' -f3)

  # backup mode
  if [ "${RUN_MODE}" = "backup" ];
  then
    # tar.gz mode
    if [ -d "${APP_PATH}" -a "${APP_MODE}" = "tar" ];
    then
      rm "${BACKUP_DIR}/${APP_NAME}.tar.gz"
      cd "${APP_PATH}"
      tar -zcvf "${BACKUP_DIR}/${APP_NAME}.tar.gz" *
    fi

    # directory mode
    if [ -d "${APP_PATH}" -a "${APP_MODE}" = "dir" ];
    then
      rmdir --parents "${BACKUP_DIR}/${APP_NAME}"
      mkdir "${BACKUP_DIR}/${APP_NAME}"
      cp --recursive ${APP_PATH}/* "${BACKUP_DIR}/${APP_NAME}"
    fi
  fi

  # restore mode
  if [ "${RUN_MODE}" = "restore" ];
  then
    # tar.gz mode
    if [ -f "${BACKUP_DIR}/${APP_NAME}.tar.gz" -a "${APP_MODE}" = "tar" ];
    then
      [ -d "${APP_PATH}" ] || mkdir --parents "${APP_PATH}"
      rm --recursive ${APP_PATH}/*
      cd "${APP_PATH}"
      tar -zxvf "${BACKUP_DIR}/${APP_NAME}.tar.gz"
    fi

    # directory mode
    if [ -d "${BACKUP_DIR}/${APP_NAME}" -a "${APP_MODE}" = "dir" ];
    then
      [ -d "${APP_PATH}" ] || mkdir --parents "${APP_PATH}"
      rm --recursive ${APP_PATH}/*
      cp --recursive ${BACKUP_DIR}/${APP_NAME}/* "${APP_PATH}"
    fi
  fi
done
