#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install gnome environment
#
# 06/06/2016, V1.0 - Creation
# -------------------------------------------------------

# install gnome classic session
logger "gnome-fallback - gnome classic session"
sudo apt -y install gnome-session-flashback gnome-tweak-tool

# install nautilus-actions
logger "gnome-fallback - nautilus-actions"
sudo apt -y install nautilus-action

# nautilus : remove nautilus action root menu
logger "gnome-fallback - remove nautilus action root menu"
mv $HOME/.config/nautilus-actions/nautilus-actions.conf $HOME/.config/nautilus-actions/nautilus-actions.conf.org
cat $HOME/.config/nautilus-actions/nautilus-actions.conf.org | sed 's/items-create-root-menu=.*/items-create-root-menu=false/' > $HOME/.config/nautilus-actions/nautilus-actions.conf

# nautilus : add new empty files right click menu
logger "gnome-fallback - add new empty files right click menu"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/nautilus-newfile-install.sh
chmod +x ./nautilus-newfile-install.sh
./nautilus-newfile-install.sh
rm nautilus-newfile-install.sh

# tweak to allow nautilus windows resize under compiz
logger "gnome-fallback - allow nautilus windows resize under compiz"
mkdir --parents $HOME/.config/gtk-3.0
wget -O $HOME/.config/gtk-3.0/gtk.css --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/config/gtk.css
wget -O $HOME/.config/gtk-3.0/settings.ini --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/config/settings.ini
mkdir --parents $HOME/.config/gtk-2.0
wget -O $HOME/.config/gtk-2.0/gtkrc --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/config/gtkrc

# console management of gnomeshell extensions
logger "gnome-fallback - console management of gnomeshell extensions"
sudo wget --header='Accept-Encoding:none' -O /usr/local/bin/gnomeshell-extension-manage https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-manage
sudo chmod +x /usr/local/bin/gnomeshell-extension-manage
