#!/bin/sh
# -------------------------------------------------------
# Script to install gnome environment
#
# 06/06/2016, V1.0 - Creation
# -------------------------------------------------------

# install gnome classic session
sudo apt-get -y install gnome-session-flashback gnome-tweak-tool

# install nautilus-action
sudo apt-get -y install nautilus-action

# nautilus : remove nautilus action root menu
mv $HOME/.config/nautilus-actions/nautilus-actions.conf $HOME/.config/nautilus-actions/nautilus-actions.conf.org
cat $HOME/.config/nautilus-actions/nautilus-actions.conf.org | sed 's/items-create-root-menu=.*/items-create-root-menu=false/' > $HOME/.config/nautilus-actions/nautilus-actions.conf

# nautilus : add new empty files right click menu
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/nautilus-newfile-install.sh
. ./nautilus-newfile-install.sh
rm nautilus-newfile-install.sh

# tweak to allow nautilus windows resize under compiz
wget -O $HOME/.config/gtk-3.0/gtk.css --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/config/gtk.css

# console management of gnomeshell extensions
sudo wget --header='Accept-Encoding:none' -O /usr/local/bin/gnomeshell-extension-install https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-install
