#!/bin/sh
# -------------------------------------------------------
# Script to configure GnomeShell environment
#
# 16/08/2016, V1.0 - Creation
# -------------------------------------------------------

# install gnome shell extensions
sudo apt-get -y install gnome-shell-extensions 

# install nautilus-action
sudo apt-get -y install nautilus-action

# console management of gnomeshell extensions
sudo wget -O /usr/local/bin/gnomeshell-extension-install "https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-install"

# gnome shell window bar icons
gsettings set org.gnome.shell.overrides button-layout :close,minimize,maximize

# enable icons for menus and icons
gsettings set org.gnome.desktop.interface menus-have-icons true
gsettings set org.gnome.desktop.interface buttons-have-icons true

# nautilus : remove nautilus action root menu
mv $HOME/.config/nautilus-actions/nautilus-actions.conf $HOME/.config/nautilus-actions/nautilus-actions.conf.org
cat $HOME/.config/nautilus-actions/nautilus-actions.conf.org | sed 's/items-create-root-menu=.*/items-create-root-menu=false/' > $HOME/.config/nautilus-actions/nautilus-actions.conf

# nautilus : add new empty files right click menu
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/nautilus-newfile-install.sh
. ./nautilus-newfile-install.sh
