#!/bin/bash
# -------------------------------------------------------
# Script to install graphical tools
#
# 15/05/2016, V1.0 - Migrated from Trusty
# 16/05/2016, V1.1 - Add SweetHome3D and update to latest version
# 12/08/2016, V1.2 - Replace image-resize by image-convert
# 13/08/2016, V1.3 - Add raw-thumbnailer
# 15/09/2016, V1.4 - Add EXIF nautilus extensions
# 22/08/2017, V1.5 - Add RAW processing tools
# -------------------------------------------------------

# misc graphical apps
logger "graphical - graphical apps"
sudo apt-get -y install exiv2 gcolor2 imagemagick dcraw

# eye of gnome viewer
logger "graphical - eye of gnome viewer"
sudo apt-get -y install eog

# hugin panorama
logger "graphical - hugin panorama"
sudo apt-get -y install hugin

# gimp
logger "graphical - gimp"
sudo apt-get -y install gimp gimp-plugin-registry

# Sweet Home 3D
logger "graphical - Sweet Home 3D"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/tools/sweethome3d-install.sh
chmod +x ./sweethome3d-install.sh
./sweethome3d-install.sh
rm sweethome3d-install.sh

# JPEG fast thumbnailer
logger "graphical - JPEG fast thumbnailer"
wget --header='Accept-Encoding:none'https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/jpeg/jpeg-thumbnailer-install.sh
chmod +x ./jpeg-tumbnailer-install.sh
./jpeg-tumbnailer-install.sh
rm jpeg-tumbnailer-install.sh

# GIMP XCF thumbnailer
logger "graphical - GIMP XCF thumbnailer"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/gimp/gimp-tumbnailer-install.sh
chmod +x ./gimp-tumbnailer-install.sh
./gimp-tumbnailer-install.sh
rm gimp-tumbnailer-install.sh

# Graphviz DOT thumbnailer
logger "graphical - Graphviz DOT thumbnailer"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/graphviz/graphviz-thumbnailer-install.sh
chmod +x ./graphviz-thumbnailer-install.sh
./graphviz-thumbnailer-install.sh
rm graphviz-thumbnailer-install.sh

# RAW pictures thumbnailer
logger "graphical - RAW pictures thumbnailer"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/raw/raw-thumbnailer-install.sh
chmod +x ./raw-thumbnailer-install.sh
./raw-thumbnailer-install.sh
rm raw-thumbnailer-install.sh

# Image convert extension
logger "graphical - Image convert extension"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-convert-install.sh
chmod +x ./image-convert-install.sh
./image-convert-install.sh
rm image-convert-install.sh

# scan2folder tool
logger "graphical - scan2folder"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/scanner/scan2folder-install.sh
chmod +x ./scan2folder-install.sh
./scan2folder-install.sh
rm scan2folder-install.sh

# file manager EXIF extensions
logger "graphical - file manager EXIF extensions"
sudo apt-get -y install python-nautilus python3-gi gir1.2-gexiv2-0.10 python-geopy
mkdir --parents $HOME/.local/share/nautilus-python/extensions
wget --header='Accept-Encoding:none' -O $HOME/.local/share/nautilus-python/extensions/exif-columns.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/exif-columns.py
wget --header='Accept-Encoding:none' -O $HOME/.local/share/nautilus-python/extensions/exif-alltags.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/exif-alltags.py
wget --header='Accept-Encoding:none' -O $HOME/.local/share/nautilus-python/extensions/exif-geotag.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/exif-geotag.py

# Luminance HDR and RAW Therapee
logger "graphical - Luminance HDR & RAW Therapee"
sudo add-apt-repository -y ppa:dhor/myway
sudo apt update
sudo apt -y install luminance-hdr
sudo apt -y install rawtherapee
