#!/bin/sh
# -------------------------------------------------------
# Script to install graphical tools
#
# 15/05/2016, V1.0 - Migrated from Trusty
# 16/05/2016, V1.1 - Add SweetHome3D and update to latest version
# -------------------------------------------------------

# misc graphical apps
sudo apt-get -y install exiv2 gcolor2 imagemagick dcraw

# eye of gnome viewer
sudo apt-get -y install eog

# hugin panorama
sudo apt-get -y install hugin

# gimp
sudo apt-get -y install gimp gimp-plugin-registry

# sweethome3d
sudo apt-get install sweethome3d sweethome3d-furniture sweethome3d-furniture-nonfree
sudo mv /usr/share/sweethome3d/sweethome3d.jar /usr/share/sweethome3d/org-sweethome3d.jar
wget -O /usr/share/sweethome3d/sweethome3d.jar https://sourceforge.net/projects/sweethome3d/files/SweetHome3D/SweetHome3D-5.2/SweetHome3D-5.2.jar/download

# GIMP XCF thumbnailer
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/gimp/gimp-tumbnailer-install.sh
. ./gimp-tumbnailer-install.sh

# Graphviz DOT thumbnailer
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/graphviz/graphviz-thumbnailer-install.sh
. ./graphviz-thumbnailer-install.sh

# Image resize extension
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-resize-install.sh
. ./image-resize-install.sh

# Image levels optimize extension
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-level-optimize-install.sh
. ./image-level-optimize-install.sh

# Image IPTC tag manager extension
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-iptc-install.sh
. ./image-iptc-install.sh

# scan2folder tool
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/scanner/scan2folder-install.sh
. ./scan2folder-install.sh
