#!/usr/bin/env bash
# ----------------------------------------------------------------
# Script to install internet tools
#
# 20/12/2015, V1.0 - Migrated from Trusty
# 20/05/2016, V1.1 - Add Whatsie
# 20/08/2016, V1.2 - Change Telegram from PPA to direct download
# 05/10/2016, V1.3 - Add SyncThing
# 29/03/2017, V1.4 - Add TeamViewer
# ----------------------------------------------------------------

# curl
sudo apt-get -y install curl

# network tools
sudo apt-get -y install nmap snmp snmp-mibs-downloader

# thunderbird
sudo apt-get -y install thunderbird-gnome-support

# chromium & filezilla
sudo apt-get -y install chromium-browser filezilla

# youtube-dl & gui
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install youtube-dl youtube-dlg

# youtubedl-gui
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/video/youtubedl-gui-install.sh
. ./youtubedl-gui-install.sh
rm youtubedl-gui-install.sh

# skype 4.3
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
sudo apt-get update
sudo apt-get -y install skype

# whatsapp client whatsie
sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 1537994D
echo "deb http://dl.bintray.com/aluxian/deb stable main" | sudo tee /etc/apt/sources.list.d/whatsie.list
sudo apt-get update
sudo apt-get -y install whatsie

# telegram client
[ "${ARCHI}" = "amd64" ] && TELEGRAM_URL="https://tdesktop.com/linux" || TELEGRAM_URL="https://tdesktop.com/linux32"
wget -O tsetup.tar.xz "${TELEGRAM_URL}"
mkdir $HOME/.TelegramDesktop
tar xf tsetup.tar.xz -C "$HOME/.TelegramDesktop"
rm tsetup.tar.xz
$HOME/.TelegramDesktop/Telegram/Telegram &
chmod +x $HOME/.local/share/applications/telegramdesktop.desktop

# Syncthing (release channel)
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
sudo apt-get update
sudo apt-get -y install syncthing
sudo systemctl enable syncthing@${USER}.service
sudo systemctl start syncthing@${USER}.service
