#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install internet tools
#
# 20/12/2015, V1.0 - Migrated from Trusty
# 20/05/2016, V1.1 - Add Whatsie
# -------------------------------------------------------

# network tools
sudo apt-get -y install nmap snmp snmp-mibs-downloader

# thunderbird
sudo apt-get -y install thunderbird-gnome-support

# chromium & filezilla
sudo apt-get -y install chromium-browser filezilla

# youtube-dl & gui
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install youtube-dl youtube-dlg

# skype 4.3
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
sudo apt-get update
sudo apt-get -y install skype

# whatsapp client whatsie
sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 1537994D
echo "deb http://dl.bintray.com/aluxian/deb stable main" | sudo tee /etc/apt/sources.list.d/whatsie.list
sudo apt-get update
sudo apt-get -y install whatsie

# telegram client
sudo add-apt-repository -y ppa:atareao/telegram
sudo apt-get update
sudo apt-get -y install telegram
