#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install internet tools
#
# 20/12/2015, V1.0 - Migrated from Trusty
# -------------------------------------------------------

# nmap
sudo apt-get -y install nmap

# thunderbird
sudo apt-get -y install thunderbird thunderbird-locale-fr thunderbird-gnome-support

# chromium & filezilla
sudo apt-get -y install chromium-browser filezilla

# youtube-dl & gui
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install youtube-dl youtube-dlg

# skype 4.3
sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"
sudo apt-get update
sudo apt-get -y install skype

# telegram client (launch Telegram from command line once to get desktop declaration)
sudo add-apt-repository -y ppa:atareao/telegram
sudo apt-get update
sudo apt-get -y install telegram
