#!/bin/sh
# -------------------------------------------------------
# Script to install office tools
#
# 20/12/2015, V1.0 - Migrated from Trusty
# 04/05/2016, V1.1 - Add Simple Note client
# -------------------------------------------------------

# grisbi
sudo apt-get -y install grisbi

# hplip
sudo apt-get -y install hplip-gui

# ocr client and french langage
sudo apt-get -y install tesseract-ocr-fra aspell-fr

# gramps (genealogy)
sudo apt-get -y install gir1.2-gexiv2-0.10 gir1.2-osmgpsmap-1.0 gramps

# PDF editor
wget --header='Accept-Encoding:none' http://get.code-industry.net/public/master-pdf-editor-3.7.02_${ARCHI}.deb
sudo gdebi --n master-pdf-editor*.deb

# Simple Note
URL_DEB=$(wget -O - https://simplenote.com/ | grep "download" | grep ".deb" | sed 's/.*\(https.*.deb\).*/\1/')
wget -O simplenote.deb ${URL_DEB}
sudo dpkg -i simplenote.deb

# declare file association 
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text application/msword
xdg-mime default libreoffice-calc.desktop application/vnd.oasis.opendocument.spreadsheet application/vnd.ms-excel

# LibreOffice thumbnailer
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/libreoffice/lo-thumbnailer-install.sh
. ./lo-thumbnailer-install.sh

# Ms Office thumbnailer
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/msoffice/msoffice-thumbnailer-install.sh
. ./msoffice-thumbnailer-install.sh

# PDF repair extension
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-repair-install.sh
. ./pdf-repair-install.sh

# PDF booklet generation extension
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/generate-booklet-install.sh
. ./generate-booklet-install.sh

# PDF document generation from multiple files
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-generate-install.sh
. ./pdf-generate-install.sh
