#!/bin/bash
# -------------------------------------------------------
#  Ubuntu 16.04 LTS Post-installation script
#
#  This script will run some commands as sudo
# 
#  20/12/2015, V1.0 - Migrated from Trusty
#  16/05/2016, V1.1 - GTK tweak to allow Nautilus windows resize
# -------------------------------------------------------

# ---------------------------------------------------
# ------------- User defined variable ---------------
# ---------------------------------------------------

DISTRINAME="xenial"

# ---------------------------------------------------
# ------------ Architecture detection ---------------
# ---------------------------------------------------

RESULT=$(uname -a | grep x86_64)
[ "$RESULT" != "" ] && ARCHI="amd64" || ARCHI="i386"
[ "$ARCHI" = "amd64" ] && X86ARCHI="64" || X86ARCHI="32"

# ---------------------------------------------------
# -------------- Disable sudo timeout ---------------
# ---------------------------------------------------

sudo sh -c 'echo "\nDefaults timestamp_timeout=-1" >> /etc/sudoers'

# ---------------------------------------------------
# --------------- Full System Update ----------------
# ---------------------------------------------------

sudo apt-get update
sudo apt-get -y dist-upgrade

# ---------------------------------------------------
# ----------------- Common Packages  ----------------
# ---------------------------------------------------

# wifi tweaks
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/wifi
chmod +x ./wifi
. ./wifi

# misc utilities and tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/utilities
chmod +x ./utilities
. ./utilities

# office tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/office
chmod +x ./office
. ./office

# graphical tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/graphical
chmod +x ./graphical
. ./graphical

# multimedia tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/multimedia
chmod +x ./multimedia
. ./multimedia

# internet tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/internet
chmod +x ./internet
. ./internet

# android tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/android
chmod +x ./android
. ./android

# remote assistance
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/assistance
chmod +x ./assistance
. ./assistance

# ---------------------------------------------------
# ---------------- Specific packages ----------------
# ---------------------------------------------------

# gnome classic session
sudo apt-get -y install gnome-session-flashback gnome-tweak-tool

# ---------------------------------------------------
# ---------------------  Tweaks  --------------------
# ---------------------------------------------------

# tweak to allow nautilus windows resize under compiz
wget -O $HOME/.config/gtk-3.0/gtk.css --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRINAME}/config/gtk.css

# touchpad : add palm detection in /etc/rc.local
sed 's/.*exit 0.*/# touchpad options\n&/' /etc/rc.local | sudo tee /etc/rc.local
sed 's/.*exit 0.*/synclient PalmDetect=1\n&/' /etc/rc.local | sudo tee /etc/rc.local
sed 's/.*exit 0.*/synclient PalmMinWidth=4\n&/' /etc/rc.local | sudo tee /etc/rc.local
sed 's/.*exit 0.*/\n&/' /etc/rc.local | sudo tee /etc/rc.local

# ---------------------------------------------------
# ------------------ Package cleanup ----------------
# ---------------------------------------------------

# packages
sudo apt-get -y autoremove
sudo apt-get -y autoclean

# purge thumbnails cache
rm -r $HOME/.thumbnails

# ---------------------------------------------------
# -------------- Enable sudo timeout ---------------
# ---------------------------------------------------

sudo sed -i "/Defaults timestamp_timeout=-1/d" /etc/sudoers
