#!/bin/sh
# -------------------------------------------------------
# Script to install misc utilities & tools
#
# 20/12/2015, V1.0 - Migrated from Trusty
# -------------------------------------------------------

# yad editor (used by many scripts)
sudo apt-get -y install yad

# system extension really needed
sudo apt-get -y install linux-firmware-nonfree xbacklight preload

# package management tools
sudo apt-get -y install ppa-purge synaptic gdebi deborphan

# filesystem clients
sudo apt-get -y install cifs-utils autofs exfat-fuse

# compression tools
sudo apt-get -y install p7zip-full rar unrar unzip

# file comparison
sudo apt-get -y install meld

# disk tools
sudo apt-get -y install smartmontools disktype unetbootin gparted

# keepassx : electronic wallet
sudo apt-get -y install keepassx

# alacarte : menu editor
sudo apt-get -y install alacarte

# photorec and qphotorec (recovery of files from SDCard)
#sudo apt-get -y install testdisk
#wget --header='Accept-Encoding:none' http://heanet.dl.sourceforge.net/project/crunchyiconthem/QPhotoRec/qphotorec_1.0_all.deb
#sudo gdebi --n qphotorec_1.0_all.deb
