#!/bin/sh
# -------------------------------------------------------
# Script to tweak wifi cards
#
# 07/05/2015, V1.0 - Migrated from Trusty
# -------------------------------------------------------

# Intel Centrino N 6235
# Re-enable AMPDU for iwldvm devices
# Solves very slow connection since kernel 3.11.10+
echo "options iwlwifi 11n_disable=8 bt_coex_active=0" | sudo tee /etc/modprobe.d/iwlwifi-11n.conf

# RTL8723be
# Solves stability issue on HP Stream 13
echo "options rtl8723be fwlps=0 swlps=0 ips=0 swenc=1" | sudo tee /etc/modprobe.d/rtl8723be.conf

# RTL8821ae
# Solves stability issues on Lenovo Ideapad 110
HAS_RTL8821AE=$(lspci | grep "RTL8821AE")
if [ "${HAS_RTL8821AE}" != "" ]
then
  # install compilation environment
  sudo apt-get install linux-headers-generic build-essential git
  
  # compile driver from source
  git clone http://github.com/lwfinger/rtlwifi_new.git
  cd rtlwifi_new
  make
  sudo make install
fi
