#!/usr/bin/env bash
# ----------------------------------------------------------------
#
# Script to install internet tools on 26.04
#
# 19/03/2026, v1.0 - Migrated from 24.04
# 21/03/2026, v1.1 - Add apparmor patch for firefox
# 15/04/2026, v1.2 - Enable Web Serial on Chromium
#
# ----------------------------------------------------------------

# set apparmor needed acces for Firefox snap
wget https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/mozilla/apparmor-firefox-install.sh
if [ -f ./apparmor-firefox-install.sh ]
then
  logger "internet - Set apparmor needed acces for Firefox snap"
  chmod +x ./apparmor-firefox-install.sh
  ./apparmor-firefox-install.sh
  rm ./apparmor-firefox-install.sh
fi

# youtube-dl replaced by yt-dlp
sudo wget -O "/usr/local/bin/yt-dlp" https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux
sudo chmod +x "/usr/local/bin/yt-dlp"

# chromium and filezilla
logger "internet - chromium & filezilla"
sudo apt -y install chromium-browser filezilla

# enable web serial on chromium
sudo snap connect chromium:raw-usb

# telegram
logger "internet - telegram"
sudo snap install telegram-desktop

# whatsapp web
# should be now installed as chromium web app
