#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install misc utilities & tools on 24.04
#
# 07/12/2024, v1.0 - Migration from 22.04
# 20/09/2026, v1.1 - Add gedit
#
# -------------------------------------------------------

# htop and iotop
logger "utilities - htop and iotop"
sudo apt -y install htop iotop

# serial terminal client
sudo usermod -aG dialout ${USERNAME}
sudo apt -y install gtkterm

# editor
sudo apt -y install gedit

# zeroconf tools
logger "utilities - zeroconf"
sudo apt -y install avahi-discover

# network tools
logger "utilities - network tools"
sudo apt -y install curl net-tools fping

# yad editor (used by many scripts)
logger "utilities - yad"
sudo apt -y install yad

# package management tools
logger "utilities - package management"
sudo apt -y install ppa-purge synaptic gdebi

# disk tools & filesystem clients
logger "utilities - disk tools & filesystem clients"
sudo apt -y install gparted
sudo apt -y install smbclient cifs-utils exfat-fuse

# compression tools
logger "utilities - compression"
sudo apt -y install rar unrar zstd

# alacarte : menu editor
logger "utilities - alacarte"
sudo apt -y install alacarte

# keepassxc : electronic wallet
sudo add-apt-repository -y ppa:phoerious/keepassxc
sudo apt -y install keepassxc
sudo systemctl daemon-reload

