#!/bin/bash
# -------------------------------------------------------
# Script to install android tools
#
# 02/06/2018, V1.0 - Migrated and tested from Xenial
# 30/09/2018, V1.1 - Add GSConnect
# -------------------------------------------------------

# adb and fastboot
logger "android - adb and fastboot"
sudo apt -y install android-tools-adb android-tools-fastboot

# install GSConnect Gnomeshell plugin
logger "android - GSConnect"
gnomeshell-extension-manage --install --user --extension-id 1319 --version latest

# declare complementary devices
logger "android - complementary devices"
sudo wget -O /etc/udev/rules.d/51-android.rules https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/51-android.rules
sudo chmod a+r /etc/udev/rules.d/51-android.rules
sudo wget -O /etc/udev/rules.d/69-mtp.rules https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/69-mtp.rules
sudo chmod a+r /etc/udev/rules.d/69-mtp.rules
mkdir --parent ~/.android
wget -O ~/.android/adb_usb.ini https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/adb_usb.ini

# APK thumbnailer
logger "android - APK thumbnailer"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/apk/apk-thumbnailer-install.sh
if [ -f ./apk-thumbnailer-install.sh ]
then
  chmod +x ./apk-thumbnailer-install.sh
  ./apk-thumbnailer-install.sh
  rm ./apk-thumbnailer-install.sh
fi

# file manager APK extensions
logger "android - file manager APK extensions"
mkdir --parents $HOME/.local/share/nautilus-python/extensions
wget -O $HOME/.local/share/nautilus-python/extensions/apk-columns.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/apk-columns.py
wget -O $HOME/.local/share/nautilus-python/extensions/apk-properties.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/apk-properties.py

# android scrcpy utility
logger "android - scrcpy utility"
sudo snap install scrcpy
sudo wget -O /usr/share/applications/scrcpy.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/scrcpy.desktop

# android screenshot utility
logger "android - screenshot utility"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/android-screenshot-install.sh
if [ -f ./android-screenshot-install.sh ]
then
  chmod +x ./android-screenshot-install.sh
  ./android-screenshot-install.sh
  rm ./android-screenshot-install.sh
fi

# QtABD
logger "android - QtABD"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/qtadb-install.sh
if [ -f ./qtadb-install.sh ]
then
  chmod +x ./qtadb-install.sh
  ./qtadb-install.sh
  rm ./qtadb-install.sh
fi
