#!/bin/bash
# -------------------------------------------------------
# Script to install graphical tools
#
# 28/04/2018, V1.0 - Migrated from Xenial
# -------------------------------------------------------

# misc graphical apps
logger "graphical - graphical apps"
sudo apt -y install exiv2 imagemagick dcraw

# hugin panorama
logger "graphical - hugin panorama"
sudo apt -y install hugin

# gimp
logger "graphical - gimp"
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp-edge
sudo apt -y install gimp

# Sweet Home 3D
logger "graphical - Sweet Home 3D"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/tools/sweethome3d/sweethome3d-install.sh
chmod +x ./sweethome3d-install.sh
./sweethome3d-install.sh
rm sweethome3d-install.sh

# JPEG fast thumbnailer
logger "graphical - JPEG fast thumbnailer"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/jpeg/jpeg-thumbnailer-install.sh
chmod +x ./jpeg-thumbnailer-install.sh
./jpeg-thumbnailer-install.sh
rm jpeg-thumbnailer-install.sh

# GIMP XCF thumbnailer
logger "graphical - GIMP XCF thumbnailer"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/gimp/gimp-tumbnailer-install.sh
chmod +x ./gimp-tumbnailer-install.sh
./gimp-tumbnailer-install.sh
rm gimp-tumbnailer-install.sh

# Graphviz DOT thumbnailer
logger "graphical - Graphviz DOT thumbnailer"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/graphviz/graphviz-thumbnailer-install.sh
chmod +x ./graphviz-thumbnailer-install.sh
./graphviz-thumbnailer-install.sh
rm graphviz-thumbnailer-install.sh

# RAW pictures thumbnailer
logger "graphical - RAW pictures thumbnailer"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/raw/raw-thumbnailer-install.sh
chmod +x ./raw-thumbnailer-install.sh
./raw-thumbnailer-install.sh
rm raw-thumbnailer-install.sh

# Image convert extension
logger "graphical - Image convert extension"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-convert-install.sh
chmod +x ./image-convert-install.sh
./image-convert-install.sh
rm image-convert-install.sh

# scan2folder tool
logger "graphical - scan2folder"
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/scanner/scan2folder-install.sh
chmod +x ./scan2folder-install.sh
./scan2folder-install.sh
rm scan2folder-install.sh

# file manager EXIF extensions
logger "graphical - file manager EXIF extensions"
sudo apt-get -y install python-nautilus python3-gi gir1.2-gexiv2-0.10 python-geopy
mkdir --parents $HOME/.local/share/nautilus-python/extensions
wget -O $HOME/.local/share/nautilus-python/extensions/exif-columns.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/exif-columns.py
wget -O $HOME/.local/share/nautilus-python/extensions/exif-alltags.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/exif-alltags.py
wget -O $HOME/.local/share/nautilus-python/extensions/exif-geotag.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/extensions/exif-geotag.py

# Luminance HDR and RAW Therapee
logger "graphical - Luminance HDR & RAW Therapee"
sudo apt -y install luminance-hdr rawtherapee
