#!/bin/bash
# ----------------------------------------------------------------
# Script to install internet tools on Bionic
#
# 30/05/2018, V1.0 - Migrated from Xenial
# ----------------------------------------------------------------

# curl
logger "internet - curl"
sudo apt -y install curl

# network tools
logger "internet - nmap and snmp"
sudo apt -y install nmap snmp snmp-mibs-downloader

# firefox extension manager
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/mozilla/firefox-extension-manager-install.sh
if [ -f ./firefox-extension-manager-install.sh ]
then
  logger "internet - firefox extension manager"
  chmod +x ./firefox-extension-manager-install.sh
  ./firefox-extension-manager-install.sh
  rm ./firefox-extension-manager-install.sh
fi
# firefox gnomeshell extensions integration
firefox-extension-manager --install --user --url https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/
sudo apt -y install chrome-gnome-shell

# firefox downloadhelper extension
HELPER_URL=$(wget -O - https://github.com/mi-g/vdhcoapp/releases | grep "vdhcoapp/releases/download/" | grep "amd64.deb" | head -n 1 | cut -d'"' -f2)
wget -O downloadhelper.deb "https://github.com${HELPER_URL}"
if [ -f ./downloadhelper.deb ]
then
  logger "internet - firefox downloadhelper extension"
  sudo dpkg -i ./downloadhelper.deb
  rm ./downloadhelper.deb
fi

# chromium and filezilla
logger "internet - chromium & filezilla"
sudo apt -y install chromium-browser filezilla

# whatsapp client whatsie
wget -O whatsie.deb https://github.com/gsantner/whatsie/releases/download/v2.1.0/whatsie-2.1.0-linux-amd64.deb
if [ -f ./whatsie.deb ]
then
  logger "internet - whatsie"
  sudo dpkg -i ./whatsie.deb
  sudo apt -y -f install
  rm ./whatsie.deb
fi

# telegram
sudo add-apt-repository -y ppa:atareao/telegram
sudo apt update
sudo apt -y install telegram

# skype
flatpak -y install https://flathub.org/repo/appstream/com.skype.Client.flatpakref

# TeamViewer
wget -O teamviewer.deb https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
if [ -f ./teamviewer.deb ]
then
  logger "assistance - TeamViewer"
  sudo dpkg -i ./teamviewer.deb
  sudo apt -y -f install
  rm ./teamviewer.deb
fi

# Syncthing (release channel)
logger "internet - Syncthing"
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
echo "deb http://apt.syncthing.net/ syncthing release" | sudo tee /etc/apt/sources.list.d/syncthing.list
sudo apt update
sudo apt -y install syncthing
sudo systemctl enable syncthing@${USER}.service
sudo systemctl start syncthing@${USER}.service
mkdir --parents $HOME/.local/share/icons
wget -O $HOME/.local/share/icons/syncthing.png  https://github.com/NicolasBernaerts/icon/raw/master/syncthing.png
