#!/usr/bin/env bash
# ---------------------------------------------------------------------------------
#  Ubuntu Bionic 18.04 LTS Post-installation script
#
#  This script will run some commands as sudo
# 
#  29/05/2018, V1.0 - Migrated from Xenial
#  30/09/2018, V1.1 - Add --no-junk option
#  15/04/2019, V1.2 - Change --wifi to --tweaks
#  16/04/2019, V1.3 - Add --arduino
#  11/11/2019, V1.4 - Add --design
# ---------------------------------------------------------------------------------

# ---------------------------------------------------
# ------------- User defined variable ---------------
# ---------------------------------------------------

DISTRI_NAME="bionic"

# ---------------------------------------------------
# ------------ Distribution detection ---------------
# ---------------------------------------------------

RESULT=$(cat /etc/lsb-release | grep "DISTRIB_CODENAME" | cut -d'=' -f2-)
[ "${RESULT}" != "${DISTRI_NAME}" ] && { echo "Distribution is ${RESULT}. This script is for ${DISTRI_NAME}"; exit 1; }

# ---------------------------------------------------
# ------------ Architecture detection ---------------
# ---------------------------------------------------

RESULT=$(uname -a | grep x86_64)
[ "${RESULT}" != "" ] && ARCHI="amd64" || ARCHI="i386"
[ "${ARCHI}" = "amd64" ] && X86ARCHI="64" || X86ARCHI="32"

# ---------------------------------------------------
# -------------- Parameters handling ----------------
# ---------------------------------------------------

# help message if no parameter
if [ ${#} -eq 0 ];
then
    echo "Script to finalise Ubuntu ${DISTRI_NAME} installation."
    echo "It will install some important packages not provided by default installation."
    echo "Options are :"
    echo "  --no-junk         Remove junk packages"
    echo "  --design          Install design apps"
    echo "  --docky           Add docky launcher"
    echo "  --arduino         Install Arduino environment (with Tasmota)"
    echo "  --tweaks          Add some tweaks for problematic hardware"
    echo "  --ssd             Add some tweaks for SSD disk"
    echo "  --hp-printer      Add HP printer GUI"
    exit 1
fi

# iterate thru parameters
while test ${#} -gt 0
do
    case $1 in
        --no-junk) NOJUNK="ok"; shift; ;;
        --design) DESIGN="ok"; shift; ;;
        --docky) DOCKY="ok"; shift; ;;
        --arduino) ARDUINO="ok"; shift; ;;
        --tweaks) TWEAKS="ok"; shift; ;;
        --ssd) SSD="ok"; shift; ;;
        --hp-printer) HPPRINTER="ok"; shift; ;;
        *) shift; ;;
    esac
done

# ---------------------------------------------------
# -------------- Disable sudo timeout ---------------
# ---------------------------------------------------

sudo sh -c 'echo "\nDefaults timestamp_timeout=-1" >> /etc/sudoers'

# ---------------------------------------------------
# --------------- Full System Update ----------------
# ---------------------------------------------------

sudo apt update
sudo apt -y upgrade

# ---------------------------------------------------
# ------------------  Gnome Shell  ------------------
# ---------------------------------------------------

# gnomeshell
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/gnomeshell
if [ -f ./gnomeshell ]
then
    chmod +x ./gnomeshell
    ./gnomeshell
    rm ./gnomeshell
fi

# ---------------------------------------------------
# ----------------- Common Packages  ----------------
# ---------------------------------------------------

# utilities and tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/utilities
if [ -f ./utilities ]
then
    chmod +x ./utilities
    ./utilities
    rm ./utilities
fi

# office tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/office
if [ -f ./office ]
then
    chmod +x ./office
    ./office
    rm ./office
fi

# graphical tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/graphical
if [ -f ./graphical ]
then
    chmod +x ./graphical
    ./graphical
    rm ./graphical
fi

# multimedia tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/multimedia
if [ -f ./multimedia ]
then
    chmod +x ./multimedia
    ./multimedia
    rm ./multimedia
fi

# internet tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/internet
if [ -f ./internet ]
then
    chmod +x ./internet
    ./internet
    rm ./internet
fi

# android tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/android
if [ -f ./android ]
then
    chmod +x ./android
    ./android
    rm ./android
fi

# ---------------------------------------------------
# -----------------  Common options  ----------------
# ---------------------------------------------------

# disable apport crash report
sudo systemctl disable apport.service

# design apps
if [ "${DESIGN}" = "ok" ]
then
    wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/design
    if [ -f ./design ]
    then
        chmod +x ./design
        ./design
        rm ./design
    fi
fi

# tweaks
if [ "${TWEAKS}" = "ok" ]
then
    wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/tweaks
    if [ -f ./tweaks ]
    then
        chmod +x ./tweaks
        ./tweaks
        rm ./tweaks
    fi
fi

# SSD tweaks
if [ "${SSD}" = "ok" ]
then
    wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/ssd
    if [ -f ./ssd ]
    then
        chmod +x ./ssd
        ./ssd
        rm ./ssd
    fi
fi

# docky : add desktop launcher
if [ "${DOCKY}" = "ok" ]
then
    wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/tools/docky-install.sh
    if [ -f ./docky-install.sh ]
    then
        chmod +x ./docky-install.sh
        ./docky-install.sh
        rm ./docky-install.sh
    fi
fi

# arduino
if [ "${ARDUINO}" = "ok" ]
then
    wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/${DISTRI_NAME}/arduino
    if [ -f ./arduino ]
    then
        chmod +x ./arduino
        ./arduino
        rm ./arduino
    fi
fi

# HP printer GUI 
if [ "${HPPRINTER}" = "ok" ]
then
    logger "hp printer - hplip"
    sudo apt -y install hplip-gui
fi

# Junk removal
if [ "${NOJUNK}" = "ok" ]
then
    # remove Amazon web launcher
    logger "no junk - amazon"
    sudo apt -y purge ubuntu-web-launchers
fi


# ---------------------------------------------------
# ------------------ Package cleanup ----------------
# ---------------------------------------------------

# packages
sudo apt -y autoremove
sudo apt -y autoclean

# purge thumbnails cache
[ -d $HOME/.thumbnails ] && rm -r $HOME/.thumbnails/*
[ -d $HOME/.cache/thumbnails ] && rm -r $HOME/.cache/thumbnails/*

# ---------------------------------------------------
# -------------- Enable sudo timeout ---------------
# ---------------------------------------------------

sudo sed -i "/Defaults timestamp_timeout=-1/d" /etc/sudoers
