#!/usr/bin/env bash
# -------------------------------------------------------
# Script to apply different tweaks for Bionic
#  - wifi
#  - touchpad
#
# 02/06/2018, V1.0 - Migrated from Xenial
# 15/04/2019, V1.1 - Add synaptics touchpad
# 31/01/2020, V1.2 - Add SSH keepalive
# 30/04/2020, V1.3 - Add Google DNS servers
# -------------------------------------------------------

# force Google DNS servers on DHCP networks
echo "DNS=8.8.8.8 8.8.4.4" | sudo tee -a /etc/systemd/resolved.conf
echo "Cache=no" | sudo tee -a /etc/systemd/resolved.conf

# SSH keepalive
echo "ClientAliveInterval 30" | sudo tee -a /etc/ssh/sshd_config
echo "ClientAliveCountMax 2" | sudo tee -a /etc/ssh/sshd_config

# RTL8723be : Solves stability issue on HP Stream 13
# RTL8821ae : Solves stability issues on Lenovo Ideapad 110
HAS_RTL8723BE=$(lspci | grep "RTL8723BE")
HAS_RTL8821AE=$(lspci | grep "RTL8821AE")
if [ "${HAS_RTL8723BE}" != "" -o "${HAS_RTL8821AE}" != "" ]
then
  # install compilation environment
  logger "wifi - RTL8723be & RTL8821ae"
  sudo apt-get install -y linux-headers-generic build-essential git
  sudo apt-get install -y libelf-dev
  
  # create temporary directory
  TMP_DIR=$(mktemp -d)
  
  # clone git repository
  pushd "${TMP_DIR}"
  git clone http://github.com/lwfinger/rtlwifi_new.git

  # compile driver from source
  pushd rtlwifi_new
  make
  sudo make install
  popd
  
  # remove temporary directory
  popd
  sudo rm -R ${TMP_DIR}
fi

# Synaptics touchpad not recognised on Acer Swift 7
HAS_SYNAPTICS=$(dmesg | grep "psmouse" | grep "synaptics" | grep "intertouch")
if [ "${HAS_SYNAPTICS}" != "" ]
then
  # un-blacklist i2c_i801 module
  sudo sed -i "s/blacklist i2c_i801/#blacklist i2c_i801/g" /etc/modprobe.d/blacklist.conf
  
  # create rc.local if needed and make it executable
  [ ! -f /etc/rc.local ] && echo '#!/bin/sh -e' | sudo tee /etc/rc.local
  sudo chmod +x /etc/rc.local
  
  # load touchpad driver with proper option
  echo "" | sudo tee -a /etc/rc.local
  echo "# synaptics touchpad" | sudo tee -a /etc/rc.local
  echo "modprobe -r psmouse" | sudo tee -a /etc/rc.local
  echo "modprobe psmouse synaptics_intertouch=1" | sudo tee -a /etc/rc.local
fi

