#!/bin/bash
# -------------------------------------------------------
# Script to install misc utilities & tools on Bionic
#
# 27/04/2018, v1.0 - Migrated from Xenial
# 08/09/2018, v1.1 - Add flatpak
# -------------------------------------------------------

# curl
logger "utilities - curl"
sudo apt -y install curl

# flatpak
logger "utilities - flatpak"
sudo apt -y install flatpak
sudo apt -y install gnome-software-plugin-flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# yad editor (used by many scripts)
logger "utilities - yad"
sudo apt -y install yad

# system extension really needed
logger "utilities - system extension"
sudo apt -y install xbacklight preload

# package management tools
logger "utilities - package management"
sudo apt -y install ppa-purge synaptic gdebi deborphan

# filesystem clients
logger "utilities - filesystem"
sudo apt -y install cifs-utils autofs exfat-fuse

# compression tools
logger "utilities - compression"
sudo apt -y install p7zip-full p7zip-rar rar unrar

# file comparison
logger "utilities - file comparison"
sudo apt -y install meld

# disk tools
logger "utilities - disk"
sudo apt -y install smartmontools disktype gparted

# easyssh
flatpak -y install https://flathub.org/repo/appstream/com.github.muriloventuroso.easyssh.flatpakref

# etcher
logger "utilities - etcher"
echo "deb https://dl.bintray.com/resin-io/debian stable etcher" | sudo tee '/etc/apt/sources.list.d/etcher.list'
sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 379CE192D401AB61
sudo apt update
sudo apt -y install etcher-electron

# alacarte : menu editor
logger "utilities - alacarte"
sudo apt -y install alacarte

# keepassxc : electronic wallet
wget -O keepassxc.deb https://github.com/magkopian/keepassxc-debian/releases/download/2.3.1-1/keepassxc_2.3.1-1_amd64_stable_stretch.deb
if [ -f ./keepassxc.deb ]
then
  logger "utilities - keepassxc"
  sudo apt -y install libykpers-1-1
  sudo gdebi --non-interactive ./keepassxc.deb
  sudo apt-get -y -f install
  rm ./keepassxc.deb
fi

# photorec and qphotorec (recovery of files from SDCard)
wget -O qphotorec.deb https://datapacket.dl.sourceforge.net/project/crunchyiconthem/QPhotoRec/qphotorec_1.0_all.deb
if [ -f ./qphotorec.deb ]
then
  logger "utilities - photorec and qphotorec"
  sudo apt -y install testdisk
  sudo gdebi --non-interactive ./qphotorec.deb
  rm ./qphotorec.deb
fi

# nitroshare
sudo apt -y install nitroshare nitroshare-nautilus
gnomeshell-extension-manage --user --install --extension-id 615
