#!/usr/bin/env bash
# ----------------------------------------------------------------
# Script to install internet tools on Jammy
#
# 22/08/2022, v1.0 - Migrated from Focal
# 04/09/2022, v1.1 - Replace Firefox snap by Mozilla PPA
# ----------------------------------------------------------------

# network tools
#logger "internet - nmap and snmp"
#sudo apt -y install nmap snmp snmp-mibs-downloader

# replace snap firefox by official mozilla deb
sudo snap remove --purge firefox
echo "Package: *" | sudo tee /etc/apt/preferences.d/mozilla-firefox
echo "Pin: release o=LP-PPA-mozillateam" | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
echo "Pin-Priority: 1001" | sudo tee -a /etc/apt/preferences.d/mozilla-firefox
echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
sudo add-apt-repository -y ppa:mozillateam/ppa
sudo apt install firefox

# firefox extension manager
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/mozilla/firefox-extension-manager-install.sh
if [ -f ./firefox-extension-manager-install.sh ]
then
  logger "internet - firefox extension manager"
  chmod +x ./firefox-extension-manager-install.sh
  ./firefox-extension-manager-install.sh
  rm ./firefox-extension-manager-install.sh
fi

# youtube-dl replaced by yt-dlp
sudo wget -O "/usr/local/bin/yt-dlp" https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux
sudo chmod +x "/usr/local/bin/yt-dlp"

# chromium and filezilla
logger "internet - chromium & filezilla"
sudo apt -y install chromium-browser filezilla

# telegram
logger "internet - telegram"
sudo apt -y install telegram-desktop

# whatsapp web
logger "internet - whatsapp"
sudo snap install whatsapp-for-linux

# Google drive Ocam
sudo add-apt-repository -y ppa:alessandro-strada/ppa
sudo apt -y install google-drive-ocamlfuse
sudo wget -O /usr/local/bin/gdrive-mount https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/gdrive-mount
sudo chmod +x /usr/local/bin/gdrive-mount

# Syncthing (release channel)
#logger "internet - Syncthing"
#sudo apt install syncthing
#sudo systemctl enable syncthing@${USER}.service
#sudo systemctl start syncthing@${USER}.service
#mkdir --parents $HOME/.local/share/icons
#wget -O $HOME/.local/share/icons/syncthing.png  https://github.com/NicolasBernaerts/icon/raw/master/syncthing.png
