#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install multimedia tools for Yammy
#
# 23/08/2022, V1.0 - Migrated from Focal
# -------------------------------------------------------

# auto-accept mscorefonts eula and install it
logger "multimedia - auto-accept mscorefonts eula"
sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
sudo apt -y install ttf-mscorefonts-installer

# restricted codecs and flash
logger "multimedia - restricted codecs & flash"
sudo apt -y install ubuntu-restricted-extras ffmpeg libavcodec-extra libavfilter-extra x264 x265

# misc audio tools
logger "multimedia - audio tools"
sudo apt -y install soundconverter lame easytag id3v2
sudo snap install mp3gain

# AAC Gain
sudo add-apt-repository -y ppa:robert-tari/main
sudo apt -y install aacgain

# CD ripping
logger "multimedia - cd ripping"
sudo apt -y install asunder

# easymp3gain

# audacity
logger "multimedia - audacity"
sudo apt -y install audacity

# MKV toolnix
logger "multimedia - MKV toolnix"
sudo apt -y install mkvtoolnix mkvtoolnix-gui

# handbrake video transcoder
logger "multimedia - handbrake"
sudo add-apt-repository -y ppa:stebbins/handbrake-releases
sudo apt -y install handbrake-gtk

# kdenlive video editor
logger "multimedia - kdenlive"
sudo add-apt-repository -y ppa:kdenlive/kdenlive-stable
sudo apt -y install kdenlive

# audio recorder
logger "multimedia - audio recorder"
sudo add-apt-repository -y ppa:audio-recorder/ppa
sudo apt -y install audio-recorder

# vlc
logger "multimedia - vlc"
sudo snap install vlc

# Convert video to MKV container and transcode audio to AAC
logger "multimedia - convert video to MKV"
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/video/video-convert2mkvaac-install.sh
chmod +x ./video-convert2mkvaac-install.sh
./video-convert2mkvaac-install.sh
rm ./video-convert2mkvaac-install.sh

# Video Stabilizer based on MLT and vid.stab
#logger "multimedia - video stabilizer"
#wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/video/video-stabilize-install.sh
#chmod +x ./video-stabilize-install.sh
#./video-stabilize-install.sh
#rm ./video-stabilize-install.sh
