#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install office tools on Jammy
#
# 22/08/2022, v1.0 - Migrated from Focal
# 06/09/2022, v1.1 - Add Master PDF Editor 4
# 09/07/2024, v1.2 - Add NAPS2 scanner
# 11/07/2024, v1.3 - Google drive PDF opening bug 
# -------------------------------------------------------

# Remove AppArmor rule to open PDF from Google Drive
sudo apparmor_parser -R /etc/apparmor.d/usr.bin.evince

# HP printer GUI 
sudo apt -y install hplip-gui

# NAPS2 scanner
wget -O naps2.deb https://github.com/cyanfish/naps2/releases/download/v7.4.3/naps2-7.4.3-linux-x64.deb
if [ -f ./naps2.deb ]
then
  logger "office - NAPS2 scanner"
  sudo gdebi -n ./naps2.deb
  rm ./naps2.deb
fi

# master PDF editor
wget -O master-pdf-editor.deb https://code-industry.net/public/master-pdf-editor-4.3.89_qt5.amd64.deb
if [ -f ./master-pdf-editor.deb ]
then
  logger "office - Master PDF Editor"
  sudo gdebi -n ./master-pdf-editor.deb
  rm ./master-pdf-editor.deb
fi

# libreoffice PPA
logger "office - libreoffice"
sudo add-apt-repository -y ppa:libreoffice/ppa
sudo apt -y upgrade

# grisbi
#logger "office - grisbi"
#sudo apt -y install grisbi

# tesseract-ocr client and french langage
#logger "office - tesseract-ocr"
#sudo apt -y install tesseract-ocr-fra aspell-fr

# gramps (genealogy)
#logger "office - gramps"
#sudo apt -y install gramps

# Thumbnailer - LibreOffice
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/libreoffice/lo-thumbnailer-install.sh
if [ -f ./lo-thumbnailer-install.sh ]
then
  logger "office - LibreOffice thumbnailer"
  chmod +x ./lo-thumbnailer-install.sh
  ./lo-thumbnailer-install.sh
  rm ./lo-thumbnailer-install.sh
fi

# Thumbnailer - Ms Office thumbnailer
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/msoffice/msoffice-thumbnailer-install.sh
if [ -f ./msoffice-thumbnailer-install.sh ]
then
  logger "office - Ms Office thumbnailer"
  chmod +x ./msoffice-thumbnailer-install.sh
  ./msoffice-thumbnailer-install.sh
  rm ./msoffice-thumbnailer-install.sh
fi

# PDF : document merge extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-merge-install.sh
if [ -f ./pdf-merge-install.sh ]
then
  logger "office - PDF document merge"
  chmod +x ./pdf-merge-install.sh
  ./pdf-merge-install.sh
  rm ./pdf-merge-install.sh
fi

# PDF : rotation extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-rotate-install.sh
if [ -f ./pdf-rotate-install.sh ]
then
  logger "office - PDF rotation extension"
  chmod +x ./pdf-rotate-install.sh
  ./pdf-rotate-install.sh
  rm ./pdf-rotate-install.sh
fi

# PDF : misc tools extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-tools-install.sh
if [ -f ./pdf-tools-install.sh ]
then
  logger "office - PDF tools extension"
  chmod +x ./pdf-tools-install.sh
  ./pdf-tools-install.sh
  rm ./pdf-tools-install.sh
fi

# PDF : booklet generation extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-booklet-install.sh
if [ -f ./pdf-booklet-install.sh ]
then
  logger "office - PDF booklet"
  chmod +x ./pdf-booklet-install.sh
  ./pdf-booklet-install.sh
  rm ./pdf-booklet-install.sh
fi

# FSearch
#sudo add-apt-repository -y ppa:christian-boxdoerfer/fsearch-stable
#sudo apt update
#sudo apt install fsearch
