#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install office tools on Focal
#
# 22/08/2022, V1.0 - Migrated from Focal
# -------------------------------------------------------

# HP printer GUI 
sudo apt -y install hplip-gui

# libreoffice PPA
logger "office - libreoffice"
sudo add-apt-repository -y ppa:libreoffice/ppa
sudo apt -y upgrade

# grisbi
logger "office - grisbi"
wget -O grisbi-common.deb https://sourceforge.net/projects/grisbi/files/grisbi%20stable/2.0.x/2.0.5/Ubuntu%2020.04/grisbi-common_2.0.5-1_all.deb/download
wget -O grisbi.deb https://sourceforge.net/projects/grisbi/files/grisbi%20stable/2.0.x/2.0.5/Ubuntu%2020.04/grisbi_2.0.5-1_amd64.deb/download
sudo gdebi --n ./grisbi-common.deb
sudo gdebi --n ./grisbi.deb
rm ./grisbi-common.deb ./grisbi.deb

# tesseract-ocr client and french langage
logger "office - tesseract-ocr"
sudo apt -y install tesseract-ocr-fra aspell-fr

# gramps (genealogy)
logger "office - gramps"
sudo apt -y install gramps

# Master PDF editor

# Thumbnailer - LibreOffice
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/libreoffice/lo-thumbnailer-install.sh
if [ -f ./lo-thumbnailer-install.sh ]
then
  logger "office - LibreOffice thumbnailer"
  chmod +x ./lo-thumbnailer-install.sh
  ./lo-thumbnailer-install.sh
  rm ./lo-thumbnailer-install.sh
fi

# Thumbnailer - Ms Office thumbnailer
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/msoffice/msoffice-thumbnailer-install.sh
if [ -f ./msoffice-thumbnailer-install.sh ]
then
  logger "office - Ms Office thumbnailer"
  chmod +x ./msoffice-thumbnailer-install.sh
  ./msoffice-thumbnailer-install.sh
  rm ./msoffice-thumbnailer-install.sh
fi

# PDF : document merge extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-merge-install.sh
if [ -f ./pdf-merge-install.sh ]
then
  logger "office - PDF document merge"
  chmod +x ./pdf-merge-install.sh
  ./pdf-merge-install.sh
  rm ./pdf-merge-install.sh
fi

# PDF : rotation extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-rotate-install.sh
if [ -f ./pdf-rotate-install.sh ]
then
  logger "office - PDF rotation extension"
  chmod +x ./pdf-rotate-install.sh
  ./pdf-rotate-install.sh
  rm ./pdf-rotate-install.sh
fi

# PDF : misc tools extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-tools-install.sh
if [ -f ./pdf-tools-install.sh ]
then
  logger "office - PDF tools extension"
  chmod +x ./pdf-tools-install.sh
  ./pdf-tools-install.sh
  rm ./pdf-tools-install.sh
fi

# PDF : booklet generation extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf/pdf-booklet-install.sh
if [ -f ./pdf-booklet-install.sh ]
then
  logger "office - PDF booklet"
  chmod +x ./pdf-booklet-install.sh
  ./pdf-booklet-install.sh
  rm ./pdf-booklet-install.sh
fi

# FSearch
sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-stable
sudo apt update
sudo apt install fsearch
