#!/bin/sh
# ---------------------------------------------------
# Thumbnailer for APK archives files
# Uses aapt (renamed as aapt-thumbnailer)
#
# Depends on :
# * unzip
# * imagemagick
# Parameters :
# $1 - full path of APK archive
# $2 - full path of generated thumbnail
# $3 - height of thumbnail in pixels
# Revision history :
# 04/08/2013, V1.0 - Creation by N. Bernaerts
# 11/08/2013, V1.1 - Use aapt to get icon file
# ---------------------------------------------------
# get parameters
INPUT=$1
OUTPUT=$2
HEIGHT=$3
# get application icon
ICON=`aapt-thumbnailer d badging "$INPUT" | grep application-icon | tail -n 1 | sed 's/^.*:.\(.*\).$/\1/'`
# if icon exists, extract icon & generate thumbnail
if [ "$ICON" != "" ] ;
then
unzip -p "${INPUT}" "${ICON}" | convert -resize x${HEIGHT} - "${OUTPUT}"
fi
