#!/bin/sh
# ---------------------------------------------------
#  Thumbnailer for APK archives files
#  Display icon and version
#  Depends on :
#    * unzip
#    * imagemagick (for convert)
#    * aapt
#  Parameters :
#    $1 - full path of APK archive
#    $2 - full path of generated thumbnail
#    $3 - height of thumbnail in pixels
#  Revision history :
#    04/08/2013, V1.0 - Creation by N. Bernaerts
#    11/08/2013, V1.1 - Use aapt to get icon file
#    05/11/2014, V2.0 - Add version display
#    06/11/2014, V2.1 - Don't use renamed aapt anymore
# ---------------------------------------------------

# select to display version on the icon
# set to yes to display version number on the icon
DISPLAY_VERSION="no"

# get parameters
INPUT=$1
OUTPUT=$2
HEIGHT=$3

# get version
VERSION=`aapt d badging "$INPUT" | grep versionName | sed 's/^.*versionName=.\(.*\)..*$/\1/'`

# get application icon
ICON=`aapt d badging "$INPUT" | grep "application:" | sed 's/^.*icon=.\(.*\).$/\1/'`

# if icon exists, extract icon & generate thumbnail 
if [ "$ICON" != "" ] ;
then 
  # calculate font size
  
  # if needed, add version display options
  if [ "$DISPLAY_VERSION" == "yes" ]
  then
    FONT_SIZE=`echo $HEIGHT / 5 | bc`
    DISPLAY_OPTION="-pointsize $FONT_SIZE -fill black -gravity south -undercolor white -annotate 0 \" $VERSION \""
  else
    DISPLAY_OPTION=""
  fi
  
  # generate icon
  unzip -p "${INPUT}" "${ICON}" | convert -resize x${HEIGHT} - $DISPLAY_OPTION "${OUTPUT}"
fi
