#!/usr/bin/env bash
# ----------------------------------------------------------------
# Script to install internet tools on Focal
#
# 22/05/2020, V1.0 - Migrated from Bionic
# ----------------------------------------------------------------

# network tools
logger "internet - nmap and snmp"
sudo apt -y install nmap snmp snmp-mibs-downloader

# youtube-dl replaced by yt-dlp
sudo wget -O "/usr/local/bin/yt-dlp" https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux
sudo chmod +x "/usr/local/bin/yt-dlp"

# firefox extension manager
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/mozilla/firefox-extension-manager-install.sh
if [ -f ./firefox-extension-manager-install.sh ]
then
  logger "internet - firefox extension manager"
  chmod +x ./firefox-extension-manager-install.sh
  ./firefox-extension-manager-install.sh
  rm ./firefox-extension-manager-install.sh
fi

# chromium and filezilla
logger "internet - chromium & filezilla"
sudo apt -y install chromium-browser filezilla

# telegram
logger "internet - telegram"
sudo apt -y install telegram-desktop

# Google drive Ocam
sudo add-apt-repository -y ppa:alessandro-strada/ppa
sudo apt -y install google-drive-ocamlfuse
sudo wget -O /usr/local/bin/gdrive-mount https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/gdrive-mount
sudo chmod +x /usr/local/bin/gdrive-mount

# Syncthing (release channel)
logger "internet - Syncthing"
sudo apt install syncthing
sudo systemctl enable syncthing@${USER}.service
sudo systemctl start syncthing@${USER}.service
mkdir --parents $HOME/.local/share/icons
wget -O $HOME/.local/share/icons/syncthing.png  https://github.com/NicolasBernaerts/icon/raw/master/syncthing.png
