#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install programming environment on Focal
#
# 28/05/2020, V1.0 - Migration from Bionic
# 17/07/2020, V1.1 - Add KiCad
# 17/07/2020, V1.2 - Add EspTool
# 16/05/2021, V1.3 - Add Tasmotizer
# -------------------------------------------------------

# easyssh
logger "programming - easyssh"
flatpak -y install https://flathub.org/repo/appstream/com.github.muriloventuroso.easyssh.flatpakref

#  Visual Studio Code (for PlatformIO IDE)
logger "programming - visual studio code"
sudo apt -y install python3-pip
wget -O vscode.deb https://go.microsoft.com/fwlink/?LinkID=760868
sudo gdebi --n ./vscode.deb
rm vscode.deb

# Extend inotify limits for VS Code
logger "programming - vscode tweaks"
echo "# For Visual Studio Code" | sudo tee -a /etc/sysctl.conf
echo "fs.inotify.max_user_watches=524288" | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

# esptool
logger "programming - esptool"
sudo apt -y install esptool
wget -O esptool.deb https://launchpad.net/ubuntu/+archive/primary/+files/esptool_2.8+dfsg-1_all.deb
sudo gdebi --n ./esptool.deb
rm esptool.deb

# esp32 partitionning tool
sudo wget -O /usr/local/bin/gen_esp32part.py https://raw.githubusercontent.com/espressif/esp-idf/master/components/partition_table/gen_esp32part.py
sudo chmod +x /usr/local/bin/gen_esp32part.py

# tasmotizer
pip3 install --upgrade pip
pip3 install tasmotizer
wget -O $HOME/.local/share/icons/tasmota.svg https://tasmota.github.io/docs/_media/logo.svg
wget -O $HOME/.local/share/applications/tasmotizer.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/tools/tasmotizer.desktop

# Tasmota sources (under $HOME/sources/Tasmota-master)
logger "programming - tasmota"
wget https://github.com/arendst/Tasmota/archive/master.zip
mkdir --parents  $HOME/sources
unzip master.zip -d $HOME/sources
rm master.zip

# graphviz
logger "programming - graphviz"
sudo apt -y install graphviz

# Graphviz DOT thumbnailer
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/graphviz/graphviz-thumbnailer-install.sh
if [ -f ./graphviz-thumbnailer-install.sh ]
then
  logger "programming - Graphviz DOT thumbnailer"
  chmod +x ./graphviz-thumbnailer-install.sh
  ./graphviz-thumbnailer-install.sh
  rm graphviz-thumbnailer-install.sh
fi

# kicad electronic diagram editor
logger "programming - kicad"
sudo add-apt-repository --yes ppa:kicad/kicad-5.1-releases
sudo apt update
sudo apt install --install-recommends kicad

# file comparison
logger "programming - file comparison"
sudo apt -y install meld
