#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install misc utilities & tools on Focal
#
# 22/05/2020, v1.0 - Migrated from Bionic
# -------------------------------------------------------

# network tools
logger "utilities - network tools"
sudo apt -y install curl net-tools fping

# flatpak
logger "utilities - flatpak"
sudo apt -y install flatpak gnome-software-plugin-flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# yad editor (used by many scripts)
logger "utilities - yad"
sudo apt -y install yad

# package management tools
logger "utilities - package management"
sudo apt -y install ppa-purge synaptic gdebi deborphan

# disk tools & filesystem clients
logger "utilities - disk tools & filesystem clients"
sudo apt -y install gparted
sudo apt -y install smbclient cifs-utils exfat-fuse

# compression tools
logger "utilities - compression"
sudo apt -y install p7zip-rar rar unrar

# alacarte : menu editor
logger "utilities - alacarte"
sudo apt -y install alacarte

# keepassxc : electronic wallet
sudo add-apt-repository -y ppa:phoerious/keepassxc
sudo apt -y install keepassxc

