#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install android tools for 24.04
#
# 07/12/2024, v1.0 - Migration from 22.04
#                    To be tested !
# -------------------------------------------------------

# adb and fastboot
logger "android - adb and fastboot"
sudo apt -y install android-tools-adb android-tools-fastboot

# install GSConnect Gnomeshell plugin
//logger "android - GSConnect"
//gnomeshell-extension-manage --install --user --extension-id 1319 --version latest

# declare complementary devices
logger "android - complementary devices"
sudo wget -O /etc/udev/rules.d/51-android.rules https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/android/51-android.rules
sudo chmod a+r /etc/udev/rules.d/51-android.rules
sudo wget -O /etc/udev/rules.d/69-mtp.rules https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/android/69-mtp.rules
sudo chmod a+r /etc/udev/rules.d/69-mtp.rules
mkdir --parent $HOME/.android
wget -O $HOME/.android/adb_usb.ini https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/android/adb_usb.ini

# APK thumbnailer
logger "android - APK thumbnailer"
wget https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/thumbnailer/apk/apk-thumbnailer-install.sh
if [ -f ./apk-thumbnailer-install.sh ]
then
  chmod +x ./apk-thumbnailer-install.sh
  ./apk-thumbnailer-install.sh
  rm ./apk-thumbnailer-install.sh
fi

# file manager APK extensions
logger "android - file manager APK extensions"
wget https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/nautilus/nautilus-apk-install.sh
if [ -f ./nautilus-apk-install.sh ]
then
  chmod +x ./nautilus-apk-install.sh
  ./nautilus-apk-install.sh
  rm ./nautilus-apk-install.sh
fi

# android scrcpy utility
logger "android - scrcpy utility"
wget -O scrcpy.tar.gz https://github.com/Genymobile/scrcpy/releases/download/v3.2/scrcpy-linux-x86_64-v3.2.tar.gz
sudo mkdir /usr/local/bin/scrcpy
sudo tar -xvf scrcpy.tar.gz -C /usr/local/bin --strip-components 1
sudo mv /usr/local/bin/icon.png /usr/share/icons/scrcpy.png
rm scrcpy.tar.gz
sudo wget -O /usr/share/applications/scrcpy.desktop https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs/heads/master/android/scrcpy.desktop
