#!/usr/bin/env bash
# -------------------------------------------------------
# Script to install programming environment on 24.04
#
# 07/12/2024, v1.0 - Migration from 22.04
#                    To be tested !
# -------------------------------------------------------

# SSH - Asbru connexion manager
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt -y install asbru-cm 

#  Visual Studio Code (for PlatformIO IDE)
logger "programming - visual studio code"
sudo apt -y install software-properties-common apt-transport-https wget
sudo apt -y install python3-venv
wget -O- https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/vscode.gpg
echo deb [arch=amd64 signed-by=/usr/share/keyrings/vscode.gpg] https://packages.microsoft.com/repos/vscode stable main | sudo tee /etc/apt/sources.list.d/vscode.list
sudo apt update
sudo apt -y install code

# Extend inotify limits for VS Code
logger "programming - vscode tweaks"
echo "# For Visual Studio Code" | sudo tee -a /etc/sysctl.conf
echo "fs.inotify.max_user_watches=524288" | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

# Tasmotizer
sudo apt install pipx
pipx install tasmotizer
pipx ensurepath
mkdir --parent $HOME/.local/share/icons
wget -O $HOME/.local/share/icons/tasmota.svg https://tasmota.github.io/docs/_media/logo.svg
wget -O $HOME/.local/share/applications/tasmotizer.desktop klet https://github.com/NicolasBernaerts/ubuntu-scripts/raw/refs//master/tools/tasmotizer.desktop

# EspTool and tasmota helper scripts
wget https://raw.githubusercontent.com/NicolasBernaerts/tasmota/master/tools/tasmota-tools-install.sh
if [ -f ./tasmota-tools-install.sh ]
then
  logger "programming - EspTool and tasmota helpers"
  chmod +x ./tasmota-tools-install.sh
  ./tasmota-tools-install.sh
  rm tasmota-tools-install.sh
fi

# Tasmota device manager
python3 -m pip install --upgrade pip
pip install PyQtWebEngine
pip install tdmgr

# Rpi imager
sudo snap install rpi-imager

# Graphviz
logger "programming - graphviz"
sudo apt -y install graphviz

# Graphviz DOT thumbnailer
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/graphviz/graphviz-thumbnailer-install.sh
if [ -f ./graphviz-thumbnailer-install.sh ]
then
  logger "programming - Graphviz DOT thumbnailer"
  chmod +x ./graphviz-thumbnailer-install.sh
  ./graphviz-thumbnailer-install.sh
  rm graphviz-thumbnailer-install.sh
fi

# Kicad electronic diagram editor
logger "programming - kicad"
sudo add-apt-repository -y ppa:kicad/kicad-6.0-releases
sudo apt update
sudo apt install -y --install-recommends kicad

# File comparison
logger "programming - file comparison"
sudo apt -y install meld
