#!/bin/sh
# ---------------------------------------------------
# Thumbnailer for RAW files
#
# Depends on :
#   * dcraw
#   * imagemagick (convert)
#
# Parameters :
#   $1 - path of RAW file
#   $2 - full path of generated thumbnail
#   $3 - height of thumbnail in pixels
#
# Revision history :
#   12/08/2016, V1.0 - Creation by N. Bernaerts
# ---------------------------------------------------

# check tools availability 
command -v dcraw >/dev/null 2>&1 || exit 1
command -v convert >/dev/null 2>&1 || exit 1

# get parameters
FILE_PATH=$1
FILE_THUMB=$2
HEIGHT=$3

# generate temporary filename
TMP_JPG=$(mktemp -t XXXXXXXX.jpg)
TMP_PPM=$(mktemp -t XXXXXXXX.ppm)

# try to extract JPG thumbnail embeded in RAW file
dcraw -c -e "${FILE_PATH}" > "${TMP_JPG}"

# if file has no thumbnail, convert to half size PPM with high speed options
[ ! -s ${TMP_JPG} ] && dcraw -c -h -q 0 "${FILE_PATH}" > "${TMP_PPM}"

# convert either JPG or PPM to final thumbnail
[ -s ${TMP_JPG} ] && convert -resize x${HEIGHT} "${TMP_JPG}" "${FILE_THUMB}" || convert -resize x${HEIGHT} "${TMP_PPM}" "${FILE_THUMB}"

# remove temporary  files
rm -f "${TMP_JPG}" "${TMP_PPM}"
