#!/bin/sh
# -------------------------------------------------------
# Script to install android tools
#
# 20/12/2014, V1.0 - Creation by N. Bernaerts
# 18/04/2015, V1.1 - Update ADB to v1.0.32
# -------------------------------------------------------

# adb and fastboot
sudo apt-get -y install android-tools-adb android-tools-fastboot
sudo wget -O /etc/udev/rules.d/51-android.rules https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/51-android.rules
sudo chmod a+r /etc/udev/rules.d/51-android.rules

# update to adb 1.0.32
wget -O - https://skia.googlesource.com/skia/+archive/cd048d18e0b81338c1a04b9749a00444597df394/platform_tools/android/bin/linux.tar.gz | tar -zxvf - adb
sudo mv adb /usr/bin/adb
sudo chmod +x /usr/bin/adb

# QtABD (to be tested)
sudo apt-get -y install libqtgui4 libqt4-network libqt4-declarative
wget  http://bernaerts.dyndns.org/download/ubuntu/qtadb/QtADB_0.8.1_linux$X86ARCHI.tar.gz
tar -xvf QtADB*.tar.gz
sudo mv ./QtADB*/QtADB /usr/local/sbin/qtadb
sudo chmod +x /usr/local/sbin/qtadb
rm -R QtADB*
mkdir -p $HOME/.config/Bracia
wget -O $HOME/.config/Bracia/QtADB.conf https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/QtADB.conf
sudo wget -O /usr/share/applications/qtadb.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/qtadb.desktop
sudo wget -O /usr/share/icons/qtadb.png http://bernaerts.dyndns.org/download/ubuntu/qtadb/qtadb.png

# APK thumbnailer
sudo apt-get -y install libfile-mimeinfo-perl gvfs-bin unzip imagemagick python-nautilus
wget http://bernaerts.dyndns.org/download/ubuntu/android-tools-aapt_4.2.2_$ARCHI.deb
sudo dpkg -i android-tools-aapt_*.deb
sudo wget -O /usr/local/sbin/apk-thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/apk-thumbnailer/apk-thumbnailer
sudo chmod +x /usr/local/sbin/apk-thumbnailer
sudo wget -O /usr/share/thumbnailers/apk.thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/apk-thumbnailer/apk.thumbnailer

# file manager APK extensions
mkdir --parents $HOME/.local/share/nautilus-python/extensions
wget -O $HOME/.local/share/nautilus-python/extensions/apk-columns.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus-extensions/apk-columns.py
wget -O $HOME/.local/share/nautilus-python/extensions/apk-properties.py https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus-extensions/apk-properties.py

# android screenshot utility
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/android-screenshot-install.sh
. ./android-screenshot-install.sh
