#!/bin/sh
# -------------------------------------------------------
# Script to install office tools
#
# 20/12/2014, V1.0 - Creation by N. Bernaerts
# -------------------------------------------------------

# PDF editor
wget http://code-industry.net/public/master-pdf-editor_1.9.25_${ARCHI}.deb
sudo gdebi --n master-pdf-editor_1.9.25_*.deb

# Libreoffice : declare 4.3 PPA & install
sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-3
sudo apt-get update
sudo apt-get -y install libreoffice libreoffice-gtk libreoffice-style-sifr

# declare file association 
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text application/msword
xdg-mime default libreoffice-calc.desktop application/vnd.oasis.opendocument.spreadsheet application/vnd.ms-excel
