#!/bin/sh
# -------------------------------------------------------
# Script to install misc utilities & tools
#
# 20/12/2014, V1.0 - Creation by N. Bernaerts
# -------------------------------------------------------

# system extension really needed
sudo apt-get -y install linux-firmware-nonfree xbacklight preload

# package management tools
sudo apt-get -y install ppa-purge synaptic gdebi

# trackpad and mouse management
sudo apt-get -y install gpointing-device-settings

# filesystem clients
sudo apt-get -y install cifs-utils autofs exfat-fuse

# compression tools
sudo apt-get -y install p7zip-full rar unrar unzip

# disk tools
sudo apt-get -y install smartmontools disktype unetbootin gparted

# snmp tools
sudo apt-get -y install snmp snmp-mibs-downloader

# keepassx : electronic wallet
sudo apt-get -y install keepassx

# alacarte : menu editor
sudo apt-get -y install alacarte

# yad editor (from WebUpd8 PPA)
sudo add-apt-repository -y ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get -y install yad
