#!/bin/sh
# -------------------------------------------------------
# Script to install office tools
#
# 20/12/2014, V1.0 - Creation by N. Bernaerts
# 22/12/2014, V1.1 - Add Gramps & dependancies
# 26/12/2014, V1.2 - Add nvpy (simple note client)
# 28/02/2015, V1.3 - Add tesseract-ocr
# -------------------------------------------------------

# grisbi
sudo apt-get -y install grisbi

# hplip
sudo apt-get -y install hplip-gui

# ocr client
sudo apt-get -y install tesseract-ocr-fra

# gramps (genealogy)
sudo apt-get -y install gir1.2-gexiv2-0.10 gir1.2-osmgpsmap-1.0
sudo apt-get -y install gramps

# PDF editor
wget http://code-industry.net/public/master-pdf-editor_2.2.15_${ARCHI}.deb
sudo gdebi --n master-pdf-editor_1.9.25_*.deb

# Libreoffice : declare 4.4 PPA & install
sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-4
sudo apt-get update
sudo apt-get -y install libreoffice libreoffice-gtk libreoffice-style-sifr

# declare file association 
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text application/msword
xdg-mime default libreoffice-calc.desktop application/vnd.oasis.opendocument.spreadsheet application/vnd.ms-excel

# LibreOffice thumbnailer
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/libreoffice/lo-thumbnailer-install.sh
. ./lo-thumbnailer-install.sh

# Ms Office thumbnailer
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/msoffice/msoffice-thumbnailer-install.sh
. ./msoffice-thumbnailer-install.sh

# PDF repair extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/pdf-repair/pdf-repair-install.sh
. ./pdf-repair-install.sh

# PDF booklet generation extension
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/generate-booklet/generate-booklet-install.sh
. ./generate-booklet-install.sh

# nvpy
sudo apt-get -y install nvpy
cp /usr/share/doc/nvpy/examples/nvpy-example.cfg $HOME/.nvpy.cfg
sudo wget -O /usr/share/icons/simplenote.png https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nvpy/simplenote.png
wget -O $HOME/.local/share/applications/nvpy.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nvpy/nvpy.desktop
