#!/bin/sh
# -------------------------------------------------------
# Script to install multimedia tools
#
# 20/12/2014, V1.0 - Creation by N. Bernaerts
# 29/01/2015, V1.1 - Add video stabilizer and MKV converter
# 07/05/2015, V1.2 - Add Kodi
# -------------------------------------------------------

# auto-accept mscorefonts eula
sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"

# restricted codecs & flash
sudo apt-get --yes --force-yes install ubuntu-restricted-extras libav-tools libavcodec-extra x264

# CSS DVD decryption
sudo sh /usr/share/doc/libdvdread4/install-css.sh

# misc audio tools
sudo apt-get -y install pavucontrol soundconverter

# mp3 tools
sudo apt-get -y install easymp3gain-gtk easytag id3v2 lame mp3gain

# audacity
sudo apt-get -y install audacity

# misc video tools
sudo apt-get -y install avidemux

# MKV toolnix
sudo apt-get -y install mkvtoolnix-gui

# handbrake video transcoder
sudo apt-get -y install handbrake

# kdenlive video editor
sudo apt-get -y install kdenlive

# audio recorder
sudo add-apt-repository  ppa:osmoma/audio-recorder
sudo apt-get update
sudo apt-get -y install audio-recorder

# kodi (xbmc)
sudo add-apt-repository -y ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get -y install kodi kodi-pvr-tvheadend-hts 

# vlc and declare it as replacement for gnome player
sudo add-apt-repository -y ppa:videolan/stable-daily
sudo apt-get update
sudo apt-get -y install vlc
sudo sed -i 's/totem/vlc/g' /usr/share/applications/defaults.list

# Convert video to MKV container and transcode audio to AAC
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/video/video-convert2mkv-install.sh
. ./video-convert2mkv-install.sh

# Video Stabilizer based on MLT and vid.stab
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/video/video-stabilize-install.sh
. ./video-stabilize-install.sh
