#!/bin/sh
# -------------------------------------------------------
#  UbuntuGnome 14.04 LTS Post-installation script
#
#  This script will run some commands as sudo
# 
#  25/05/2014, V1.0 - Creation by N. Bernaerts
#  20/12/2014, V2.0 - Externalize scripts
# -------------------------------------------------------

# ---------------------------------------------------
# ------------- User defined variable ---------------
# ---------------------------------------------------


# ---------------------------------------------------
# ------------ Architecture detection ---------------
# ---------------------------------------------------

RESULT=`uname -a | grep x86_64`
[ "$RESULT" != "" ] && ARCHI="amd64" || ARCHI="i386"
[ "$ARCHI" = "amd64" ] && X86ARCHI="64" || X86ARCHI="32"

# ---------------------------------------------------
# --------------- Full System Update ----------------
# ---------------------------------------------------

# packages update
sudo apt-get update
sudo apt-get -y dist-upgrade

# ---------------------------------------------------
# ----------------- Common Packages  ----------------
# ---------------------------------------------------

# misc utilities and tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty-utilities
chmod +x ./trusty-utilities
. ./trusty-utilities

# office tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty-office
chmod +x ./trusty-office
. ./trusty-office

# graphical tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty-graphical
chmod +x ./trusty-graphical
. ./trusty-graphical

# multimedia tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty-multimedia
chmod +x ./trusty-multimedia
. ./trusty-multimedia

# multimedia tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty-internet
chmod +x ./trusty-internet
. ./trusty-internet

# android tools
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty-android
chmod +x ./trusty-android
. ./trusty-android

# remote assistance
wget https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty-assistance
chmod +x ./trusty-assistance
. ./trusty-assistance

# ---------------------------------------------------
# ----------- Gnome Shell Configuration -------------
# ---------------------------------------------------

# gnome shell extensions
sudo apt-get -y install gnome-shell-extensions 

# gnome shell window bar icons
gsettings set org.gnome.shell.overrides button-layout :close,minimize,maximize


# ---------------------------------------------------
# ------------------ Package cleanup ----------------
# ---------------------------------------------------

# packages
sudo apt-get -y autoremove
sudo apt-get -y autoclean

# purge thumbnails cache
rm -r $HOME/.thumbnails

# ---------------------------------------------------
# -------------- Ubuntu Gnome tweaks ----------------
# ---------------------------------------------------

# force proper multi-display position at startup
# see http://bernaerts.dyndns.org/linux/74-ubuntu/309-ubuntu-dual-display-monitor-position-lost
sudo wget -O /usr/local/sbin/update-monitor-position https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/update-monitor-position
sudo chmod +x /usr/local/sbin/update-monitor-position
mkdir $HOME/.config/autostart
wget -O $HOME/.config/autostart/update-monitor-position.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/update-monitor-position.desktop

# ---------------------------------------------------
# ------------------- Wifi tweaks -------------------
# ---------------------------------------------------

# Intel Centrino N 6235 - Re-enable AMPDU for iwldvm devices
# Solves very slow connection since kernel 3.11.10+
echo options iwlwifi 11n_disable=8 | sudo tee /etc/modprobe.d/iwlwifi-11n.conf
echo options iwlwifi bt_coex_active=0 | sudo tee -a /etc/modprobe.d/iwlwifi-11n.conf
