#!/bin/sh
# -------------------------------------------------------
# Script to install office tools
#
# 20/12/2014, V1.0 - Creation by N. Bernaerts
# -------------------------------------------------------

# PDF editor
wget http://code-industry.net/public/master-pdf-editor_1.9.25_${ARCHI}.deb
sudo gdebi --n master-pdf-editor_1.9.25_*.deb

# Libreoffice : declare 4.3 PPA & install
sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-3
sudo apt-get update
sudo apt-get -y install libreoffice libreoffice-gtk libreoffice-style-sifr

# declare file association 
xdg-mime default libreoffice-writer.desktop application/vnd.oasis.opendocument.text application/msword
xdg-mime default libreoffice-calc.desktop application/vnd.oasis.opendocument.spreadsheet application/vnd.ms-excel

# LibreOffice thumbnailer
sudo apt-get -y install libfile-mimeinfo-perl gvfs-bin unzip imagemagick
wget http://bernaerts.dyndns.org/download/gnome/thumbnailer/lo-thumbnailer-icons.zip
sudo unzip -d /usr/local/sbin lo-thumbnailer-icons.zip
rm lo-thumbnailer-icons.zip
sudo wget -O /usr/local/sbin/lo-thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/libreoffice/lo-thumbnailer
sudo chmod +rx /usr/local/sbin/lo-thumbnailer
sudo wget -O /usr/share/thumbnailers/lo.thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/libreoffice/lo.thumbnailer

# Ms Office thumbnailer
sudo apt-get -y install libfile-mimeinfo-perl gvfs-bin unoconv imagemagick
wget http://bernaerts.dyndns.org/download/gnome/thumbnailer/msoffice-thumbnailer-icons.zip
sudo unzip -d /usr/local/sbin msoffice-thumbnailer-icons.zip
rm msoffice-thumbnailer-icons.zip
sudo wget -O /usr/local/sbin/msoffice-thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/msoffice/msoffice-thumbnailer
sudo chmod +rx /usr/local/sbin/msoffice-thumbnailer
sudo wget -O /usr/share/thumbnailers/msoffice.thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/msoffice/msoffice.thumbnailer
