#!/bin/sh
# -------------------------------------------------------
# Script to install graphical tools
#
# 20/12/2014, V1.0 - Creation by N. Bernaerts
# -------------------------------------------------------

# misc graphical apps
sudo apt-get -y install exiv2 gcolor2 imagemagick dcraw

# eye of gnome viewer
sudo apt-get -y install eog

# hugin panorama
sudo apt-get -y install hugin

# gimp : declare 2.8 PPA & install
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo apt-get update
sudo apt-get -y install gimp gimp-plugin-registry

# scan2folder tool
sudo wget -O /usr/local/bin/scan2folder https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/scan2folder/scan2folder
sudo chmod +x /usr/local/bin/scan2folder
sudo wget -O /usr/share/applications/scan2folder.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/scan2folder/scan2folder.desktop
sudo chmod +x /usr/share/applications/scan2folder.desktop
wget -O $HOME/.scan2folder.conf https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/scan2folder/scan2folder.conf

# GIMP XCF thumbnailer
sudo apt-get -y install gvfs-bin imagemagick xcftools
sudo wget -O /usr/local/sbin/gimp-thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/gimp/gimp-thumbnailer
sudo chmod +x /usr/local/sbin/gimp-thumbnailer
sudo wget -O /usr/share/thumbnailers/gimp.thumbnailer https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/thumbnailer/gimp/gimp.thumbnailer

# Image resize extension
sudo apt-get -y install imagemagick
wget -O $HOME/.image-resize.conf https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-resize.conf
sudo wget -O /usr/local/bin/image-resize https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-resize
sudo chmod +x /usr/local/bin/image-resize
sudo wget -O /usr/share/applications/image-resize.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-resize.desktop
mkdir --parents $HOME/.local/share/file-manager/actions
wget -O $HOME/.local/share/file-manager/actions/image-resize-action.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/image/image-resize-action.desktop
