#!/bin/sh
# ---------------------------------------------------
# Thumbnailer for Ms Office documents
#
# Depends on :
#   * unzip
#   * imagemagick
#   * unoconv
#   * gvfs
# Parameters :
#   $1 - URI of office file
#   $2 - full path of generated thumbnail
#   $3 - height of thumbnail in pixels
# Revision history :
# 11/11/2014, V1.0 - Creation by N. Bernaerts
# 15/11/2014, V2.0 - Change to URI and GVFS to handle thumbnails on network shares
# ---------------------------------------------------

# path where to get icons used for generation
ICONPATH="/usr/local/sbin/msoffice-thumbnailer-icons"

# get parameters
FILE_URI=$1
FILE_THUMB=$2
HEIGHT=$3

# get filename extension
FILE_EXT=$(echo "$FILE_URI" | sed 's/^.*\.\(.*\)/\1/')

# generate temporary directory
TMP_DIR=$(mktemp -d)
TMP_BASEFILE="$TMP_DIR/file"

# copy file to temporary local directory
gvfs-copy "${FILE_URI}" "${TMP_BASEFILE}.${FILE_EXT}"

# get the file mime type (application/msword, ...)
MIMETYPE=$(mimetype -b "${TMP_BASEFILE}.${FILE_EXT}")

# determine icon type according to mime type
case $MIMETYPE in 
  "application/msword" | "application/vnd.ms-word" | \
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document" )
    DOCTYPE="word"
    ;;
  "application/vnd.ms-excel" | \
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" | \
  "application/vnd.openxmlformats-officedocument.spreadsheetml.template" )
    DOCTYPE="excel"
    ;;
  "application/vnd.ms-powerpoint" | \
  "application/vnd.openxmlformats-officedocument.presentationml.presentation" | \
  "application/vnd.openxmlformats-officedocument.presentationml.template" | \
  "application/vnd.openxmlformats-officedocument.presentationml.slideshow" )
    DOCTYPE="powerpoint"
    ;;
  * )
esac

# convert first document page to PDF
unoconv -e PageRange=1-1 -f pdf -o "${TMP_BASEFILE}.pdf" "${TMP_BASEFILE}.${FILE_EXT}"

# convert PDF to PNG
convert "${TMP_BASEFILE}.pdf" "${TMP_BASEFILE}.png"

# generate thumbnail according to document type
composite -gravity center \( -resize x244 "${TMP_BASEFILE}.png" \) ${ICONPATH}/msoffice-${DOCTYPE}.png ${ICONPATH}/msoffice-mask.png \( -resize x${HEIGHT} \) "$FILE_THUMB"

# remove temporary files
rm -R $TMP_DIR
