#!/bin/bash
# ---------------------------------------------------
#  Tool to write main XMP tags to compatible files
#
#  Depends on :
#   * yad
#   * exiftool
#   * iconv
#   * convert
#
#  Revision history :
#   10/03/2014, V1.0 - Creation by N. Bernaerts
#   08/05/2015, V1.1 - Code cleanup and optimization
#   16/05/2015, V1.2 - Handle non UTF-8 tags
#   20/08/2015, V2.0 - Complete rewrite for XMP tags
#   20/08/2016, V2.1 - Mass tagging capability
# ---------------------------------------------------

# -------------------------------------------------
#          Check tools availability
# -------------------------------------------------

# check yad, exiftool, iconv and convert
command -v yad >/dev/null 2>&1 || { zenity --error --text="Please install yad"; exit 1; }
command -v exiftool >/dev/null 2>&1 || { zenity --error --text="Please install exiftool [libimage-exiftool-perl]"; exit 1; }
command -v iconv >/dev/null 2>&1 || { zenity --error --text="Please install iconv"; exit 1; }
command -v convert >/dev/null 2>&1 || { zenity --error --text="Please install convert [imagemagick]"; exit 1; }

# -------------------------------------------------------
#             Check number of arguments
# -------------------------------------------------------

# if no argument, display help
if [ $# -eq 0 ] 
then
  echo "Tool to write main XMP tags to compatible files"
  echo "Parameters are :"
  echo "  <photo1> <photo2> ...   List of picture files"
  exit
fi

# calculate number of image files
NBR_FILE=$#

# -------------------------------------------------------
#                  Initialisation
# -------------------------------------------------------

# load common functions
. tags-common

# Configuration file : ~/.config/image-tag-xmp.conf
FILE_CONF="$HOME/.config/tags-xmp.conf"

# check configuration file
[ -f "$FILE_CONF" ] || { zenity --error --text="Please create and configure ${FILE_CONF}"; exit 1; }

# load default values from configuration file
NEW_CITY=$(cat "${FILE_CONF}" | grep "city" | cut -d'=' -f2)
NEW_COUNTRY=$(cat "${FILE_CONF}" | grep "country" | cut -d'=' -f2)
NEW_AUTHOR=$(cat "${FILE_CONF}" | grep "author" | cut -d'=' -f2)
NEW_THUMBNAIL=$(cat "${FILE_CONF}" | grep "thumbnail" | cut -d'=' -f2)

# temporary files
TAG_UTF8=$(mktemp --tmpdir "XXXXXXXX.utf8")
THUMB_ORIGINAL=$(mktemp --tmpdir "XXXXXXXX.jpg")
rm -f "${TAG_UTF8}" "${THUMB_ORIGINAL}"

# -------------------------------------------------------
#              Individual file parameters
# -------------------------------------------------------

if [ ${NBR_FILE} -eq 1 ]
then
  # set input file
  INPUT_FILE="$1"

  # read EXIF data
  tags-extract-all "${TAG_UTF8}" "${INPUT_FILE}"

  # extract or generate thumbnail
  tags-get-thumbnail "${INPUT_FILE}" "${THUMB_ORIGINAL}"

  # get meta-data
  DATE=$(tags-get-date ${TAG_UTF8})
  TITLE=$(tags-get-title ${TAG_UTF8})
  CAPTION=$(tags-get-caption ${TAG_UTF8})
  KEYWORD=$(tags-get-keywords ${TAG_UTF8})
  AUTHOR=$(tags-get-author ${TAG_UTF8})
  CITY=$(tags-get-city ${TAG_UTF8})
  [ "${CITY}" = "" ] && CITY=$(cat "${FILE_CONF}" | grep "city" | cut -d'=' -f2)
  COUNTRY=$(tags-get-country ${TAG_UTF8})
  [ "${COUNTRY}" = "" ] && COUNTRY=$(cat "${FILE_CONF}" | grep "country" | cut -d'=' -f2)

  # generate the date digits and time
  YEAR=$(echo ${DATE} | cut -d' ' -f1 | cut -d ':' -f1)
  MONTH=$(echo ${DATE} | cut -d' ' -f1 | cut -d ':' -f2)
  DAY=$(echo ${DATE} | cut -d' ' -f1 | cut -d ':' -f3)
  TIME=$(echo ${DATE} | cut -d' ' -f2)
  [ "${TIME}" = "" ] && TIME="12:00:00"

  #  Display the tags editing dialog
  RESULT=$(yad --center --title="XMP Tags - ${INPUT_FILE}" --width=800 --image="${THUMB_ORIGINAL}" --date-format="%d/%m/%Y" --window-icon="gtk-edit" --form --field="Title" --field="Description" --field="City" --field="Country" --field="Date:DT" --field="Time" --field="Keywords" --field="Author" --field="Include thumbnail:CHK" "${TITLE}" "${CAPTION}" "${CITY}" "${COUNTRY}" "${DAY}/${MONTH}/${YEAR}" "${TIME}" "${KEYWORD}" "${AUTHOR}" "${NEW_THUMBNAIL}" --button="gtk-cancel:1" --button="gtk-ok:0" )
  ACTION=$?

  # if dialog has been validated, retrieve tags from dialog
  if [ ${ACTION} = "0" ]
  then
    # retreive the values from resulting chain
    NEW_TITLE=$(echo ${RESULT} |cut -d '|' -f1)
    NEW_CAPTION=$(echo ${RESULT} |cut -d '|' -f2)
    NEW_CITY=$(echo ${RESULT} |cut -d '|' -f3)
    NEW_COUNTRY=$(echo ${RESULT} |cut -d '|' -f4)
    NEW_DAY=$(echo ${RESULT} | cut -d '|' -f5 | cut -d'/' -f1)
    NEW_MONTH=$(echo ${RESULT} | cut -d '|' -f5 | cut -d'/' -f2)
    NEW_YEAR=$(echo ${RESULT} | cut -d '|' -f5 | cut -d'/' -f3)
    NEW_TIME=$(echo ${RESULT} | cut -d '|' -f6)
    NEW_KEYWORD=$(echo ${RESULT} | cut -d '|' -f7)
    NEW_AUTHOR=$(echo ${RESULT} | cut -d '|' -f8)
    NEW_THUMBNAIL=$(echo ${RESULT} | cut -d '|' -f9)

    # set time and date
    [ "${NEW_TIME}" = "" ] && NEW_TIME="12:00:00"
    [ "${NEW_YEAR}" = "" ] && NEW_DATE="" || NEW_DATE="${NEW_YEAR}:${NEW_MONTH}:${NEW_DAY} ${NEW_TIME}"
  fi

# -------------------------------------------------------
#              Mass tagging parameters
# -------------------------------------------------------

else
  # Display the mass tags editing dialog
  RESULT=$(yad --center --title="XMP tags - Mass Tagging of ${NBR_FILE} files" --width=800 --window-icon="gtk-edit" --form --field="Title" --field="Description" --field="City" --field="Country" --field="Keywords" --field="Author" --field="Include thumbnail:CHK" "" "" "${CITY}" "${COUNTRY}" "" "${AUTHOR}" "${THUMBNAIL}" --button="gtk-cancel:1" --button="gtk-ok:0")
  ACTION=$?

  # if dialog has been canceled, exit
  [ ${ACTION} = "1" ] && exit

  # dialog has not been canceled, retreive values from resulting chain
  NEW_TITLE=$(echo ${RESULT} |cut -d '|' -f1)
  NEW_CAPTION=$(echo ${RESULT} |cut -d '|' -f2)
  NEW_CITY=$(echo ${RESULT} |cut -d '|' -f3)
  NEW_COUNTRY=$(echo ${RESULT} |cut -d '|' -f4)
  NEW_KEYWORD=$(echo ${RESULT} | cut -d '|' -f5)
  NEW_AUTHOR=$(echo ${RESULT} | cut -d '|' -f6)
  NEW_THUMBNAIL=$(echo ${RESULT} | cut -d '|' -f7)
fi

# -------------------------------------------------------
#                Loop thru all images
# -------------------------------------------------------

# set progress box title
DIALOG_TITLE="XMP tags - Updating ${NBR_FILE} files"

INDEX=0
for INPUT_FILE in "$@"
do
  # if current photo is not skipped, update it
  if [ "${ACTION}" = "0" ]
  then
    # read the data embedded into the file
    echo $(((INDEX*100+20)/NBR_FILE))
    echo "# File $((INDEX+1)) / ${NBR_FILE} - Prepare Tags"
    tags-extract-all "${TAG_UTF8}" "${INPUT_FILE}"

    # if new meta-data set, get it, otherwise read original one
    [ "${NEW_DATE}"    != "" ] && DATE="${NEW_DATE}"       || DATE=$(tags-get-date ${TAG_UTF8})
    [ "${NEW_TITLE}"   != "" ] && TITLE="${NEW_TITLE}"     || TITLE=$(tags-get-title ${TAG_UTF8})
    [ "${NEW_CAPTION}" != "" ] && CAPTION="${NEW_CAPTION}" || CAPTION=$(tags-get-caption ${TAG_UTF8})
    [ "${NEW_KEYWORD}" != "" ] && KEYWORD="${NEW_KEYWORD}" || KEYWORD=$(tags-get-keywords ${TAG_UTF8})
    [ "${NEW_AUTHOR}"  != "" ] && AUTHOR="${NEW_AUTHOR}"   || AUTHOR=$(tags-get-author ${TAG_UTF8})
    [ "${NEW_CITY}"    != "" ] && CITY="${NEW_CITY}"       || CITY=$(tags-get-city ${TAG_UTF8})
    [ "${NEW_COUNTRY}" != "" ] && COUNTRY="${NEW_COUNTRY}" || COUNTRY=$(tags-get-country ${TAG_UTF8})

    # handle meta-data removal
    [ "${NEW_TITLE}"   = "-" ] && TITLE=""
    [ "${NEW_CAPTION}" = "-" ] && CAPTION=""
    [ "${NEW_KEYWORD}" = "-" ] && KEYWORD=""
    [ "${NEW_AUTHOR}"  = "-" ] && AUTHOR=""
    [ "${NEW_CITY}"    = "-" ] && CITY=""
    [ "${NEW_COUNTRY}" = "-" ] && COUNTRY=""

    # update tags
    tags-set-date "${TAG_UTF8}" "${DATE}"
    tags-set-title "${TAG_UTF8}" "${TITLE}"
    tags-set-caption "${TAG_UTF8}" "${CAPTION}"
    tags-set-city "${TAG_UTF8}" "${CITY}"
    tags-set-country "${TAG_UTF8}" "${COUNTRY}"
    tags-set-keywords "${TAG_UTF8}" "${KEYWORD}"
    tags-set-author "${TAG_UTF8}" "${AUTHOR}"

    # update EXIF tags
    echo $(((INDEX*100+40)/NBR_FILE))
    echo "# File $((INDEX+1)) / ${NBR_FILE} - Write EXIF Tags"
    tags-save-family "${TAG_UTF8}" "${INPUT_FILE}" "EXIF"

    # update XMP tags
    echo $(((INDEX*100+60)/NBR_FILE))
    echo "# File $((INDEX+1)) / ${NBR_FILE} - Write XMP Tags"
    tags-save-family "${TAG_UTF8}" "${INPUT_FILE}" "XMP"

    # if needed, update thumbnail
    if [ "${NEW_THUMBNAIL}" = "TRUE" ] 
    then
      # write thumbnail
      echo $(((INDEX*100+80)/NBR_FILE))
      echo "# File $((INDEX+1)) / ${NBR_FILE} - Write Thumbnail"
      tags-add-thumbnail "${INPUT_FILE}"
    fi
  fi

  # index increment
  INDEX=$((INDEX+1))

  # display progress
  echo $(((INDEX*100)/NBR_FILE))

done | zenity --width=400 --no-cancel --progress --auto-close --title "${DIALOG_TITLE}"

# cleanup temporary files
rm -f "${TAG_UTF8}" "${THUMB_ORIGINAL}"
