#!/bin/bash
# ---------------------------------------------------
# Daemon to detect FlashAir card communication events
# 
# Revision history :
#   30/03/2017, V1.0 - Creation by N. Bernaerts
#   14/08/2017, V2.0 - Rewrite inotify with fifo
# ---------------------------------------------------

# load flashair environment variables
. /usr/local/sbin/flashair-common

# enable recursive inotify on flashair root in daemon mode
inotifywait --recursive --daemon --quiet --event open,moved_from --outfile "${FLASHAIR_FIFO}" --exclude "/PRIVATE/" "${FLASHAIR_ROOT}"

# infinite loop to read filesystem events
while true
do
	if read FLASHAIR_EVENT; 
	then
		# analyse event data
		EVENT_PATH=$(echo "${FLASHAIR_EVENT}" | cut -d' ' -f1)
		EVENT_ACTION=$(echo "${FLASHAIR_EVENT}" | cut -d' ' -f2)
		EVENT_ELEMENT=$(echo "${FLASHAIR_EVENT}" | cut -d' ' -f3-)

		# local directory
		ELEMENT_DIR=$(echo ${EVENT_PATH} | sed "s/\/$//")
		ELEMENT_PATH="${EVENT_PATH}${EVENT_ELEMENT}"

		# action according to event
		case "${EVENT_ACTION}" in

			# a directory is being read
			"OPEN,ISDIR")
			# if 3rd argument is empty, update directory content
			[ "${EVENT_ELEMENT}" = "" ] && flashair-command --update "${ELEMENT_DIR}"
			;;

			# a file has been moved
			"MOVED_FROM")
			# remove file from the card
			flashair-command --delete "${ELEMENT_PATH}"
			;;

			# default : do nothing
			*)
			;;
		esac
	fi
done < "${FLASHAIR_FIFO}"

