#!/bin/bash
# ---------------------------------------------------
#  Flashair SD Card wifi network detection
# 
# Revision history :
#   30/03/2017, V1.0 - Creation by N. Bernaerts
# ---------------------------------------------------

# flashair environment
FLASHAIR_NAME="flashair"
FLASHAIR_DAEMON_NAME="${FLASHAIR_NAME}-daemon"
FLASHAIR_DAEMON_PATH="/usr/local/sbin/${FLASHAIR_DAEMON_NAME}"

# check if connected to flashair wifi network
FLASHAIR_NETWORK=$(iwconfig | grep "ESSID" | grep "${FLASHAIR_NAME}_")

# check if flashair daemon is running
start-stop-daemon --status --name "${FLASHAIR_DAEMON_NAME}"
RESULT=$?

# if connected to flashair wifi network
if [ "${FLASHAIR_NETWORK}" != "" ]
then
	# if daemon is not running,
	if [ "${RESULT}" != "0" ]
	then
		# call flashair connect command
		flashair-command --connect

		# start flashair daemon
		start-stop-daemon --start --background --exec "${FLASHAIR_DAEMON_PATH}"
	fi

# else, if not connected to flashair wifi network
else
	# stop flashair daemon
	start-stop-daemon --stop --name "${FLASHAIR_DAEMON_NAME}"

	# kill running inotifywait child process
	PID_INOTIFY=$(ps -ef | grep /media/flashair | grep inotifywait | xargs | cut -d ' ' -f2)
	[ "${PID_INOTIFY}" != "" ] && kill -9 ${PID_INOTIFY}

	# call flashair disconnect command
	flashair-command --disconnect
fi
