#!/bin/bash

# check flashair configuration
FLASHAIR_CONF="/etc/default/flashair.conf"
[ ! -f ${FLASHAIR_CONF} ] && { echo "Configuration file ${FLASHAIR_CONF} is mandatory to define FlashAir mount root"; exit 1; }

# get flashair card mount root
SDCARD_ROOT=$(grep "^flashair-mount=" "${FLASHAIR_CONF}" | cut -d'=' -f2-)

# infitite loop
while true
do
    # wait for event on directory
    FLASHAIR_EVENT=$(inotifywait -r "${SDCARD_ROOT}")

    # analyse event
    EVENT_PATH=$(echo "${FLASHAIR_EVENT}" | cut -d' ' -f1)
    EVENT_ACTION=$(echo "${FLASHAIR_EVENT}" | cut -d' ' -f2)
    EVENT_ELEMENT=$(echo "${FLASHAIR_EVENT}" | cut -d' ' -f3-)

    # if directory is opened, update from flashair card
    if [ "${EVENT_ACTION}" = "OPEN,ISDIR" ]
    then
        # local directory
        LOCAL_PATH="${EVENT_PATH}${EVENT_ELEMENT}"

        # call flashair command
        flashair-command --root "${SDCARD_ROOT}" "${LOCAL_PATH}"
    fi
done
