#!/bin/bash
# -------------------------------------------------------
#  Ubuntu 14.04 LTS Post-installation script
#
#  This script will run some commands as sudo
# 
#  20/12/2014, V1.0 - Creation by N. Bernaerts
#  26/12/2014, V1.1 - Timeout sudo during installation
# -------------------------------------------------------

# ---------------------------------------------------
# ------------- User defined variable ---------------
# ---------------------------------------------------

# ---------------------------------------------------
# ------------ Architecture detection ---------------
# ---------------------------------------------------

RESULT=$(uname -a | grep x86_64)
[ "$RESULT" != "" ] && ARCHI="amd64" || ARCHI="i386"
[ "$ARCHI" = "amd64" ] && X86ARCHI="64" || X86ARCHI="32"

# ---------------------------------------------------
# -------------- Disable sudo timeout ---------------
# ---------------------------------------------------

sudo sh -c 'echo "\nDefaults timestamp_timeout=-1">>/etc/sudoers'

# ---------------------------------------------------
# --------------- Full System Update ----------------
# ---------------------------------------------------

sudo apt-get update
sudo apt-get -y dist-upgrade

# ---------------------------------------------------
# ----------------- Common Packages  ----------------
# ---------------------------------------------------

# misc utilities and tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/utilities
chmod +x ./utilities
. ./utilities

# office tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/office
chmod +x ./office
. ./office

# graphical tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/graphical
chmod +x ./graphical
. ./graphical

# multimedia tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/multimedia
chmod +x ./multimedia
. ./multimedia

# internet tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/internet
chmod +x ./internet
. ./internet

# android tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/android
chmod +x ./android
. ./android

# remote assistance
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/assistance
chmod +x ./assistance
. ./assistance

# wifi tweaks
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/wifi
chmod +x ./wifi
. ./wifi

# ---------------------------------------------------
# ---------------- Specific packages ----------------
# ---------------------------------------------------

# gnome classic session
sudo apt-get -y install gnome-session-fallback gnome-tweak-tool

# ---------------------------------------------------
# ------------------ Package cleanup ----------------
# ---------------------------------------------------

# packages
sudo apt-get -y autoremove
sudo apt-get -y autoclean

# purge thumbnails cache
rm -r $HOME/.thumbnails

# ---------------------------------------------------
# -------------- Enable sudo timeout ---------------
# ---------------------------------------------------

sudo sed -i "/Defaults timestamp_timeout=-1/d" /etc/sudoers
