#!/bin/sh
# -------------------------------------------------------
#  UbuntuGnome 14.04 LTS Post-installation script
#
#  This script will run some commands as sudo
# 
#  25/05/2014, V1.0 - Creation by N. Bernaerts
#  20/12/2014, V2.0 - Externalize scripts
#  26/12/2014, V2.1 - Timeout sudo during installation
#  09/01/2015, V2.2 - Nautilus actions and icons
# -------------------------------------------------------

# ---------------------------------------------------
# ------------- User defined variable ---------------
# ---------------------------------------------------


# ---------------------------------------------------
# ------------ Architecture detection ---------------
# ---------------------------------------------------

RESULT=`uname -a | grep x86_64`
[ "$RESULT" != "" ] && ARCHI="amd64" || ARCHI="i386"
[ "$ARCHI" = "amd64" ] && X86ARCHI="64" || X86ARCHI="32"

# ---------------------------------------------------
# -------------- Disable sudo timeout ---------------
# ---------------------------------------------------

sudo sh -c 'echo "\nDefaults timestamp_timeout=-1">>/etc/sudoers'

# ---------------------------------------------------
# --------------- Full System Update ----------------
# ---------------------------------------------------

# packages update
sudo apt-get update
sudo apt-get -y dist-upgrade

# ---------------------------------------------------
# ----------------- Common Packages  ----------------
# ---------------------------------------------------

# misc utilities and tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/utilities
chmod +x ./utilities
. ./utilities

# office tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/office
chmod +x ./office
. ./office

# graphical tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/graphical
chmod +x ./graphical
. ./graphical

# multimedia tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/multimedia
chmod +x ./multimedia
. ./multimedia

# multimedia tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/internet
chmod +x ./internet
. ./internet

# android tools
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/android
chmod +x ./android
. ./android

# remote assistance
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/assistance
chmod +x ./assistance
. ./assistance

# wifi tweaks
wget --header='Accept-Encoding:none' https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/install/trusty/wifi
chmod +x ./wifi
. ./wifi

# ---------------------------------------------------
# ----------- Gnome Shell Configuration -------------
# ---------------------------------------------------

# gnome shell extensions
sudo apt-get -y install gnome-shell-extensions 

# gnome shell window bar icons
gsettings set org.gnome.shell.overrides button-layout :close,minimize,maximize

# enable nautilus actions
sudo apt-get -y install nautilus-actions 

# enable icons for menus and icons
gsettings set org.gnome.desktop.interface menus-have-icons true
gsettings set org.gnome.desktop.interface buttons-have-icons true

# ---------------------------------------------------
# ------------------ Package cleanup ----------------
# ---------------------------------------------------

# packages
sudo apt-get -y autoremove
sudo apt-get -y autoclean

# purge thumbnails cache
rm -r $HOME/.thumbnails

# ---------------------------------------------------
# -------------- Ubuntu Gnome tweaks ----------------
# ---------------------------------------------------

# force proper multi-display position at startup
# see http://bernaerts.dyndns.org/linux/74-ubuntu/309-ubuntu-dual-display-monitor-position-lost
sudo wget --header='Accept-Encoding:none' -O /usr/local/sbin/update-monitor-position https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/update-monitor-position
sudo chmod +x /usr/local/sbin/update-monitor-position
mkdir $HOME/.config/autostart
wget --header='Accept-Encoding:none' -O $HOME/.config/autostart/update-monitor-position.desktop https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/update-monitor-position.desktop

# install language selector
sudo apt-get install language-selector-gnome

# ---------------------------------------------------
# --------------- Enable sudo timeout ---------------
# ---------------------------------------------------

sudo sed -i "/Defaults timestamp_timeout=-1/d" /etc/sudoers
