#!/bin/sh
# -------------------------------------------------------
# Script to tweak wifi cards
#
# 07/05/2015, V1.0 - Creation by N. Bernaerts
# -------------------------------------------------------

# Intel Centrino N 6235
# Re-enable AMPDU for iwldvm devices
# Solves very slow connection since kernel 3.11.10+
echo "options iwlwifi 11n_disable=8 bt_coex_active=0" | sudo tee /etc/modprobe.d/iwlwifi-11n.conf

# RTL8723be
# Solves stability issue on HP Stream 13
echo "options rtl8723be fwlps=0 swlps=0 ips=0 swenc=1" | sudo tee /etc/modprobe.d/rtl8723be.conf
