#!/bin/bash
# bwrap wrapper to correct nautilus 3.26.4+ bug for external thumbnailers under debian based distros
#  * replaces --symlink calls with equivalent --ro-bind calls
#  * add --ro-bind needed by imagemagick tools

# intialise parameters array
ARR_PARAM=( )

# loop thru original parameters
while test $# -gt 0
do
	case "$1" in
		# --symlink : convert to --ro-bind
		"--symlink") shift; shift; ARR_PARAM=( "${ARR_PARAM[@]}" "--ro-bind" "$1" "$1" ); shift; ;;
		# others : add parameter
		*) ARR_PARAM=( "${ARR_PARAM[@]}" "$1" ); shift; ;;
	esac
done

# add both --ro-bind needed by thumbnailers using imagemagick tools
ARR_PARAM=( "${ARR_PARAM[@]}" "--ro-bind" "/etc/alternatives" "/etc/alternatives" "--ro-bind" "/var/cache/fontconfig" "/var/cache/fontconfig" )

# call original bwrap
/usr/bin/bwrap "${ARR_PARAM[@]}"
