#!/usr/bin/env bash
# -------------------------------------------------------------------
# Google drive mounting script using google-drive-ocamlfuse
#
#  Depends on :
#    * google-drive-ocamlfuse
# Revision history :
#   30/05/2020, V1.0 - Creation by N. Bernaerts
#   02/07/2021, V1.1 - Add controls
# -------------------------------------------------------------------

# check tools
command -v google-drive-ocamlfuse >/dev/null 2>&1 || { zenity --error --text="Please install google-drive-ocamlfuse from ppa:alessandro-strada/ppa"; exit 1; }

# if no argument, display help
if [ $# -eq 0 ] 
then
	echo "Google drive mounting script using google-drive-ocamlfuse"
	echo "Parameters are :"
	echo "  --label <label>        Google drive environment label (default by default)"
	echo "  --mount <path>         Mounting path"
	exit 1
fi

# loop to retrieve arguments
while test $# -gt 0
do
	case "$1" in
		"--label") shift; OCAM_LABEL="$1"; shift; ;;
		"--mount") shift; OCAM_MOUNT="$1"; shift; ;;
		*) shift; ;;
	esac
done

# check variables
[ "${OCAM_LABEL}" = "" ] && OCAM_LABEL="default"
[ "${OCAM_MOUNT}" = "" ] && { zenity --error --width 300 --text="Please specify mount point (--mount)"; exit 1; }

# if mount point is relative, start from home directory
[ "${OCAM_MOUNT:0:1}" != "/" ] && OCAM_MOUNT="$HOME/${OCAM_MOUNT}"

# create mount point if it doesn't exist
[ ! -d "${OCAM_MOUNT}" ] && mkdir --parent "${OCAM_MOUNT}"
[ ! -d "${OCAM_MOUNT}" ] && { zenity --error --width 400 --text="Impossible to create mount point\n(${OCAM_MOUNT})"; exit 1; }

# check if directory is already mounted
DIR_MOUNT=$(basename "${OCAM_MOUNT}")
IS_MOUNTED=$(mount | grep "google-drive-ocamlfuse" | grep "${DIR_MOUNT}")

# if drive not already mounted
if [ "${IS_MOUNTED}" = "" ]
then
	# check if mount point is empty
	LIST_FILE=$(ls "${OCAM_MOUNT}")
	[ "${LIST_FILE}" != "" ] && { zenity --error --width 400 --text="Mount point is not empty\n(${OCAM_MOUNT})"; exit 1; }

	# mount drive
	google-drive-ocamlfuse -label "${OCAM_LABEL}" "${OCAM_MOUNT}"
fi

# open nautilus
nautilus "${OCAM_MOUNT}" &
