#!/bin/bash
# ---------------------------------------------------
# Handle nautilus action to create an empty file from a model
#
# For installation instructions, please check
#  http://bernaerts.dyndns.org/linux/344-nautilus-new-document-creation-menu
#
# Revision history :
#   03/06/2016, V1.0 - Creation by N. Bernaerts
# ---------------------------------------------------

# load functions to handle INI files
. read-ini-file

# get module as parameter
SECTION=$1
DIRECTORY=$2

# configuration directory and file
CONF_ROOT="${HOME}/.config/nautilus-actions"
CONF_INI="${CONF_ROOT}/nautilus-newfile.ini"
CONF_DIR="${CONF_ROOT}/nautilus-newfile"

# get data
MODEL=$(INI_Read_Key "${CONF_INI}" "${SECTION}" model)
OPTION=$(INI_Read_Key "${CONF_INI}" "${SECTION}" option)

# copy model to current directory
[ -f "${CONF_DIR}/${MODEL}" ] && cp "${CONF_DIR}/${MODEL}" "${DIRECTORY}/${MODEL}"

# set execute bit if needed
[ "${OPTION}" = "execute" ] && chmod +x "${DIRECTORY}/${MODEL}"
