#!/usr/bin/env bash
# -------------------------------------------------------------
# Handle installation, update or removal of updated 
# gphoto libraries to avoid corrupted DCIM with latest GoPro
#
# Revision history :
#   20/06/2016, V1.0 - Creation by N. Bernaerts
#   20/07/2017, V2.0 - Complete rework to become update proof
# -------------------------------------------------------------

# if no argument, display help
if [ $# -eq 0 ] 
then
  echo "Tool to install libgphoto2 2.5.10 libraries to correct latest GoPro DCIM bug under Xenial."
  echo "Parameters are :"
  echo "  --install       Install and declare the updated library"
  echo "  --remove        Back to original library"
  echo "  --verify        Check that updated libraries are properly declared and do it if needed"
  exit
fi

# loop to retrieve arguments
while test $# -gt 0
do
  case "$1" in
    "--install") MODE="install"; shift; ;;
    "--remove") MODE="remove"; shift; ;;
    "--verify") MODE="verify"; shift; ;;
    *) shift; ;;
  esac
done

# check --update or --cleanup mode
[ "${MODE}" = "" ] && { echo "Please use --install, --remove or --verify mode"; exit 1; }

# initialisation
UPDATE="no"

# select mode
case "${MODE}" in

  # ---------------------------
  #   Installation mode
  # ---------------------------
  "install") 
	
    # remove targeted files and directories 
    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
    rm -R /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
    rm -R /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
    rm -f /lib/udev/hwdb.d/20-libgphoto2-6.hwdb

    # unpack and declare libgphoto2-port12
    wget -O /tmp/libgphoto2-port12.deb http://fr.archive.ubuntu.com/ubuntu/pool/main/libg/libgphoto2/libgphoto2-port12_2.5.10-3_amd64.deb
    dpkg --fsys-tarfile /tmp/libgphoto2-port12.deb | sudo tar xf - -C /opt/libgphoto2
    rm /tmp/libgphoto2-port12.deb
    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0

    # unpack and declare libgphoto2
    wget -O /tmp/libgphoto2.deb http://fr.archive.ubuntu.com/ubuntu/pool/main/libg/libgphoto2/libgphoto2-6_2.5.10-3_amd64.deb
    dpkg --fsys-tarfile /tmp/libgphoto2.deb | sudo tar xf - -C /opt/libgphoto2
    rm /tmp/libgphoto2.deb
    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2.so.6.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
    ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10 /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
    ln -s /opt/libgphoto2/lib/udev/hwdb.d/20-libgphoto2-6.hwdb /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
    
    # download and declare apt post install hook
    wget -O /etc/apt/apt.conf.d/99nautilus-xenial-gopro https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/nautilus/99nautilus-xenial-gopro

    # ask for hardware database and udev update
    UPDATE="yes"
    ;;

  # ---------------------------
  #   Removal mode
  # ---------------------------
  "remove")
	
    # remove targeted files and directories 
    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
    rm -R /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
    rm -f /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
    rm -R /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
    rm -f /lib/udev/hwdb.d/20-libgphoto2-6.hwdb

    # remove apt post install hook
    rm /etc/apt/apt.conf.d/99nautilus-xenial-gopro

    # reinstall original packages
    apt-get install --yes --reinstall libgphoto2-6 libgphoto2-port12

    # remove /opt/libgphoto2 directory structure
    rm -R /opt/libgphoto2

    # ask for hardware database and udev update
    UPDATE="yes"
    ;;

  # ---------------------------
  #   Verification mode
  # ---------------------------
  "verify")
	
    # if links to new libgphoto2-port12 is not present
    if [ ! -h /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12 -o ! -h /usr/lib/x86_64-linux-gnu/libgphoto2.so.6 ]
    then
      # remove targeted files and directories 
      rm -f /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
      rm -R /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
      rm -f /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
      rm -R /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
      rm -f /lib/udev/hwdb.d/20-libgphoto2-6.hwdb

      # create links
      ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port.so.12
      ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0 /usr/lib/x86_64-linux-gnu/libgphoto2_port/0.12.0
      ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2.so.6.0.0 /usr/lib/x86_64-linux-gnu/libgphoto2.so.6
      ln -s /opt/libgphoto2/usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10 /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.10
      ln -s /opt/libgphoto2/lib/udev/hwdb.d/20-libgphoto2-6.hwdb /lib/udev/hwdb.d/20-libgphoto2-6.hwdb
      
      # ask for hardware database and udev update
      UPDATE="yes"
    fi
    ;;

  *)
    ;;

esac

if [ "${UPDATE}" = "yes" ]
then
  # update hardware database
  udevadm hwdb --update

  # restart udev service
  service udev restart
fi
