#!/bin/bash
# -------------------------------------------------------------
# Declare all model files for Nautilus New File extension
#
# All models are declared in ~/.config/nautilus-newfile.conf
#
# Revision history :
#   03/06/2016, V1.0 - Creation by N. Bernaerts
#   13/08/2016, V1.1 - Add --install and --remove parameters
#   12/05/2017, V1.2 - Add new file ... action menu
# -------------------------------------------------------------

# -------------------------------------------------------
#   Loop to load arguments
# -------------------------------------------------------

# if no argument, display help
if [ $# -eq 0 ] 
then
	echo "Tool to declare Nautilus New File extension."
	echo "Parameters are :"
	echo "  --install       Install the extension"
	echo "  --remove        Remove the extension"
	exit
fi

# loop to retrieve arguments
while test $# -gt 0
do
	case "$1" in
		"--install") MODE="install"; shift; ;;
		"--remove") MODE="remove"; shift; ;;
		*) shift; ;;
	esac
done

# ---------------------------------------------------
#  Initialisation
# ---------------------------------------------------

# load functions to handle INI files
. read-ini-file

# nautilus action script
ACTION_SCRIPT=$(which "nautilus-newfile-action")

# desktop action files directory
ACTION_DIR="$HOME/.local/share/file-manager/actions"

# configuration directory and file
CONF_DIR="$HOME/.config/nautilus-actions"
CONF_INI="${CONF_DIR}/nautilus-newfile.ini"

# list sections
ARR_SECTION=( $(INI_List_Sections "${CONF_INI}") )

# ---------------------------------------------------
#  Removal
# ---------------------------------------------------

# remove all previous action desktop files
rm -f ${ACTION_DIR}/newfile-*.desktop

# ---------------------------------------------------
#  Installation
# ---------------------------------------------------

# temporary file
TMP_FILE=$(mktemp)

if [ "${MODE}" = "install" ]
then
	# ------------------------------
	#  Generate Action menu
	# ------------------------------

	# set action desktop file name
	FILE_DESKTOP="${ACTION_DIR}/newfile-menu.desktop"

	# generate items list
	ITEM_LIST=$(echo "${ARR_SECTION[@]}" | sed "s/ /;newfile-/g")
	ITEM_LIST="newfile-${ITEM_LIST};"

	# write [Desktop Entry] section
	echo "[Desktop Entry]" > "${TMP_FILE}"
	echo "Type=Menu" >> "${TMP_FILE}"
	echo "Icon=Add" >> "${TMP_FILE}"
	echo "Name[C]=New file ..." >> "${TMP_FILE}"
	echo "Tooltip[C]=Create new empty file" >> "${TMP_FILE}"
	echo "ItemsList=${ITEM_LIST}" >> "${TMP_FILE}"

	# copy file
	mv "${TMP_FILE}" "${FILE_DESKTOP}"

	# ------------------------------
	#  Generate Action files
	# ------------------------------

	# loop thru sections
	for SECTION in "${ARR_SECTION[@]}"
	do
		# get data
		LABEL=$(INI_Read_Key "${CONF_INI}" "${SECTION}" label)
		ICON=$(INI_Read_Key "${CONF_INI}" "${SECTION}" icon)

		# set action desktop file name
		FILE_DESKTOP="${ACTION_DIR}/newfile-${SECTION}.desktop"
  
		# write [Desktop Entry] section
		echo "[Desktop Entry]" > "${TMP_FILE}"
		echo "Type=Action" >> "${TMP_FILE}"
		echo "Icon=${ICON}" >> "${TMP_FILE}"
		echo "Name[C]=${LABEL}" >> "${TMP_FILE}"
		echo "Tooltip[C]=Create new ${LABEL}" >> "${TMP_FILE}"
		echo "ToolbarLabel[C]=Create new ${LABEL}" >> "${TMP_FILE}"
		echo "TargetLocation=true" >> "${TMP_FILE}"
		echo "TargetToolbar=true" >> "${TMP_FILE}"
		echo "TargetContext=false" >> "${TMP_FILE}"
		echo "MimeType=inode/directory;" >> "${TMP_FILE}"
		echo "Capabilities=Writable" >> "${TMP_FILE}"
		echo "Profiles=directory;" >> "${TMP_FILE}"
		echo "" >> "${TMP_FILE}"
  
		# write [X-Action-Profile ] section
		echo "[X-Action-Profile directory]" >> "${TMP_FILE}"
		echo "Exec=${ACTION_SCRIPT} ${SECTION} %f" >> "${TMP_FILE}"

		# copy file
		mv "${TMP_FILE}" "${FILE_DESKTOP}"
	done
fi

# remove temporary file 
rm -f ${TMP_FILE}

# ---------------------------------------------------
#  Restart nautilus
# ---------------------------------------------------

# restart nautilus to update configuration
nautilus -q
