<style type="text/css">
	body { background-color:black; }
	div.list { display:table; margin-left:10px; margin-right:0px; margin-top:5px; margin-bottom:0px; padding:0px; }
	div.text { position:absolute; z-index:1; border-radius:5px; background-color:white; opacity:0.7; }
	div.cam { float:left; display:inline; margin:3px 5px; padding:0px; }
	div.cam img { z-index:0; height:160px; border-radius:3px; }
	div.cam div.text { font-family:arial,serif; font-size:10pt; font-style:italic; padding:0px 5px; margin-top:140px; margin-left:10px; }
</style>
