#!/bin/bash
# --------------------------------------------
#  Rotate a list of image files
#
#  Depends on :
#    * mimetype (libfile-mimeinfo-perl package)
#    * jpegtran (libjpeg-turbo-progs package)
#    * pngtopnm, pnmtopng, giftopnm, ppmtogif, tifftopnm, pnmtotiff and pnmflip (netpbm package)
#
#  Revision history :
#   09/10/2017, V1.0 - Creation by N. Bernaerts
# ---------------------------------------------------

# -------------------------------------------------------
# check tools availability
# -------------------------------------------------------

# loop to retrieve arguments
while test $# -gt 0
do
	case "$1" in
	"--right") JPEG_ANGLE="90"; PNM_ANGLE="270"; shift; ;;
	"--left") JPEG_ANGLE="270"; PNM_ANGLE="90"; shift; ;;
	"--up-down") JPEG_ANGLE="180"; PNM_ANGLE="180"; shift; ;;
	*) ARR_FILE=( "${ARR_FILE[@]}" "$1" ); shift; ;;
	esac
done

# check rotation is selected
[ "${JPEG_ANGLE}" = "" ] && { zenity --error --text="Please select rotation parameter"; exit 1; }

# check tools availability
command -v mimetype >/dev/null 2>&1 || { zenity --error --text="Please install mimetype [libfile-mimeinfo-perl]"; exit 1; }
command -v jpegtran >/dev/null 2>&1 || { zenity --error --text="Please install jpegtran [libjpeg-turbo-progs]"; exit 1; }
command -v pngtopnm >/dev/null 2>&1 || { zenity --error --text="Please install pngtopnm [netpbm]"; exit 1; }
command -v pnmtopng >/dev/null 2>&1 || { zenity --error --text="Please install pnmtopng [netpbm]"; exit 1; }
command -v giftopnm >/dev/null 2>&1 || { zenity --error --text="Please install giftopnm [netpbm]"; exit 1; }
command -v ppmtogif >/dev/null 2>&1 || { zenity --error --text="Please install ppmtogif [netpbm]"; exit 1; }
command -v tifftopnm >/dev/null 2>&1 || { zenity --error --text="Please install tifftopnm [netpbm]"; exit 1; }
command -v pnmtotiff >/dev/null 2>&1 || { zenity --error --text="Please install pnmtotiff [netpbm]"; exit 1; }
command -v pnmflip >/dev/null 2>&1 || { zenity --error --text="Please install pnmflip [netpbm]"; exit 1; }

# -------------------------------------
# loop thru PDF files to convert them
# -------------------------------------

# create temporary file
TMP_PNM=$(mktemp --tmpdir XXXXXXXX-org.pnm)
TMP_ROTATE=$(mktemp --tmpdir XXXXXXXX-rot.pnm)

# loop thru files 
for FILE in "${ARR_FILE[@]}"
do
	# get file mimetype
	TYPE_FILE=$(mimetype --brief "${FILE}")

	# rotate file according to mimetype
	case "${TYPE_FILE}" in

	"image/jpeg")
		# rotate image
		jpegtran -rotate ${JPEG_ANGLE} "${FILE}" > "${TMP_ROTATE}"
		;;

	"image/png")
		# convert image to PNM
		pngtopnm "${FILE}" > "${TMP_PNM}"

		# rotate image
		pnmflip -r${PNM_ANGLE} "${TMP_PNM}" | pnmtopng - > "${TMP_ROTATE}"
		;;

	"image/gif")
		# convert image to PNM
		giftopnm "${FILE}" > "${TMP_PNM}"

		# rotate image
		pnmflip -r${PNM_ANGLE} "${TMP_PNM}" | ppmtogif - > "${TMP_ROTATE}"
		;;

	"image/tiff")
		# convert image to PNM
		tifftopnm "${FILE}" > "${TMP_PNM}" 

		# rotate image
		pnmflip -r${PNM_ANGLE} "${TMP_PNM}" | pnmtotiff - > "${TMP_ROTATE}"
		;;

	*)
		;;
	esac

	# replace original file
	[ -s "${TMP_ROTATE}" ] && mv --force "${TMP_ROTATE}" "${FILE}"

done

# remove temporary file
rm -f "${TMP_PNM}" "${TMP_ROTATE}"


