#!/bin/bash
# -------------------------------------------------------------------------------
# Declare all model files for Nautilus Image convert extension
#
# All formats are declared in ~/.config/image-convert.conf
#
# Revision history :
#   12/08/2016, V1.0 - Creation by N. Bernaerts
#   13/08/2016, V1.1 - Add --install and --remove parameters
#   17/08/2016, v1.2 - Update for Gnome 3.18, generate menu before action files
# -------------------------------------------------------------------------------

# -------------------------------------------------------
#   Loop to load arguments
# -------------------------------------------------------

# if no argument, display help
if [ $# -eq 0 ] 
then
  echo "Tool to declare Nautilus image conversion extension."
  echo "Parameters are :"
  echo "  --install       Install the extension"
  echo "  --remove        Remove the extension"
  exit
fi

# loop to retrieve arguments
while test $# -gt 0
do
  case "$1" in
    "--install") MODE="install"; shift; ;;
    "--remove") MODE="remove"; shift; ;;
    *) shift; ;;
   esac
done

# ---------------------------------------------------
#  Initialisation
# ---------------------------------------------------

# desktop action files directory
ACTION_DIR="$HOME/.local/share/file-manager/actions"

# action file
ACTION_SCRIPT="/usr/local/bin/image-convert"

# configuration file
CONVERT_CONF="$HOME/.config/image-convert.conf"

# ---------------------------------------------------
#  Removal
# ---------------------------------------------------

# remove all previous menu and action desktop files
rm -f ${ACTION_DIR}/image-convert-*.desktop

# ---------------------------------------------------
#  Installation
# ---------------------------------------------------

if [ "${MODE}" = "install" ]
then
  # -----------------------
  #  List all Action files
  # -----------------------

  # load available formats to temporary file
  FILE_TMP=$(mktemp -t format-XXXXXXXX.tmp)
  grep "=" "${CONVERT_CONF}" > "${FILE_TMP}"

  # loop thru formats
  while read LINE; do

    # get data
    NAME=$(echo "${LINE}" | cut -d"=" -f1 )

    # add desktop file to menu items list
    ITEM_LIST="${ITEM_LIST}image-convert-${NAME};"

  done < "${FILE_TMP}"

  # ----------------------
  #  Generate Menu file
  # ----------------------

  # close all nautilus instances
  nautilus -q
  
  # set menu desktop file name
  FILE_DESKTOP="${ACTION_DIR}/image-convert-menu.desktop"

  # write [Desktop Entry] section
  echo "[Desktop Entry]" > "${FILE_DESKTOP}"
  echo "Type=Menu" >> "${FILE_DESKTOP}"
  echo "Icon=emblem-photos" >> "${FILE_DESKTOP}"
  echo "Name[C]=Convert to ..." >> "${FILE_DESKTOP}"
  echo "Tooltip[C]=Tools to convert image files to various formats" >> "${FILE_DESKTOP}"
  echo "ItemsList=${ITEM_LIST}" >> "${FILE_DESKTOP}"

  # ------------------------
  #  Generate Action files
  # ------------------------

  # restart nautilus to detect root menu
  nautilus &
  sleep 5

  # loop thru formats
  while read LINE; do

    # get data
    NAME=$(echo "${LINE}" | cut -d"=" -f1 )
    LABEL=$(echo "${LINE}" | cut -d"=" -f2 | cut -d',' -f1)
    ICON=$(echo "${LINE}" | cut -d"=" -f2 | cut -d',' -f2)
    WIDTH=$(echo "${LINE}" | cut -d"=" -f2 | cut -d',' -f3)
    HEIGHT=$(echo "${LINE}" | cut -d"=" -f2 | cut -d',' -f4)
    TYPE=$(echo "${LINE}" | cut -d"=" -f2 | cut -d',' -f5)

    # set conversion title
    [ "${WIDTH}" = "-" ] && TITLE="${LABEL}" || TITLE="${LABEL} (${WIDTH}x${HEIGHT})"

    # set mimetype (exclude self type if neeeded)
    MIMETYPE="image/*;"
    [ "${WIDTH}" = "-" ] && MIMETYPE="${MIMETYPE} !image/${NAME};"

    # set action desktop file name
    FILE_DESKTOP="${ACTION_DIR}/image-convert-${NAME}.desktop"

    # write [Desktop Entry] section
    echo "[Desktop Entry]" > "${FILE_DESKTOP}"
    echo "Type=Action" >> "${FILE_DESKTOP}"
    echo "Icon=${ICON}" >> "${FILE_DESKTOP}"
    echo "Name[C]=${TITLE}" >> "${FILE_DESKTOP}"
    echo "Tooltip[C]=${TITLE}" >> "${FILE_DESKTOP}"
    echo "MimeType=${MIMETYPE}" >> "${FILE_DESKTOP}"
    echo "Capabilities=Writable" >> "${FILE_DESKTOP}"
    echo "Profiles=convert;" >> "${FILE_DESKTOP}"
    echo "" >> "${FILE_DESKTOP}"
  
    # write [X-Action-Profile ] section
    echo "[X-Action-Profile convert]" >> "${FILE_DESKTOP}"
    echo "Exec=${ACTION_SCRIPT} --format ${NAME} %F" >> "${FILE_DESKTOP}"

  done < "${FILE_TMP}"

fi

# ---------------------------------------------------
#  Restart nautilus
# ---------------------------------------------------

# restart nautilus to update configuration
nautilus -q
