#!/bin/sh
# ---------------------------------------------------
#  Thumbnailer for APK archives files
#  Display icon and version
#  Depends on :
#    * unzip
#    * imagemagick (for convert)
#    * aapt
#  Parameters :
#    $1 - full path of APK archive
#    $2 - full path of generated thumbnail
#    $3 - height of thumbnail in pixels
#  Revision history :
#    04/08/2013, V1.0 - Creation by N. Bernaerts
#    11/08/2013, V1.1 - Use aapt to get icon file
#    05/11/2014, V2.0 - Add version display
#    06/11/2014, V2.1 - Don't use renamed aapt anymore
# ---------------------------------------------------

# select to display version on the icon
# set to yes to display version number on the icon
DISPLAY_VERSION="no"

# get parameters
INPUT=$1
OUTPUT=$2
HEIGHT=$3

# get application icon
ICON=$(aapt d badging "$INPUT" | grep "application-icon" | sed 's/^.*icon-\(.*\):.\(.*\).$/\2/' | tail -1)

# if icon exists, extract icon & generate thumbnail 
if [ "$ICON" != "" ] ;
then 
  # if needed, add version display options
  if [ "$DISPLAY_VERSION" = "yes" ] ;
  then
    # get version
    VERSION=`aapt d badging "$INPUT" | grep versionName | sed 's/^.*versionName=.\(.*\)..*$/\1/'`

    # calculate optimum font size
    FONT_SIZE=`echo $HEIGHT / 5 | bc`

    # generate icon including version number
    unzip -p "${INPUT}" "${ICON}" | convert -resize x${HEIGHT} - -pointsize $FONT_SIZE -fill black -gravity south -undercolor white -annotate 0 " $VERSION " "${OUTPUT}"

  # else, generate plain icon without version number
  else
    unzip -p "${INPUT}" "${ICON}" | convert -resize x${HEIGHT} - "${OUTPUT}"
  fi
fi
