#!/bin/bash
# Command to display dialog box on latest desktop session
# If called from an interactive session, 
#   it runs the display command whithout specific behaviour
# If called from a service or a daemon, 
#   it recovers latest desktop environment from /tmp/.latest-desktop-session.ini
#   and runs the display command on this desktop environment thru DBUS
#
# Installation is described in http://bernaerts.dynds.org/....
#
# Revision history :
#   05/09/2017, V1.0 - Creation by N. Bernaerts
#   12/09/2017, V1.1 - Switch config from shell to ini file 
# -------------------------------------------------------------------

# set latest desktop session file in temporary directory
DESKTOP_TMP=$(dirname $(mktemp "XXXXXXX" -ut))
DESKTOP_SESSION="${DESKTOP_TMP}/.latest-desktop-session.ini"

# empty parameters array
ARR_DESKTOP=( )

# if process is not running in a desktop session
if [ "${DBUS_SESSION_BUS_ADDRESS}" = "" ]
then
	# if latest desktop session file exists
	if [ -f "${DESKTOP_SESSION}" ]
	then
		# load latest desktop session environment
		DESKTOP_USER=$(grep "^User=" "${DESKTOP_SESSION}" | cut -d'=' -f2-)
		DESKTOP_DISPLAY=$(grep "^Display=" "${DESKTOP_SESSION}" | cut -d'=' -f2-)
		DESKTOP_DBUS=$(grep "^DBus=" "${DESKTOP_SESSION}" | cut -d'=' -f2-)

		# fill-up array for session display parameters
		ARR_DESKTOP=("sudo" "-u" "${DESKTOP_USER}" "DISPLAY=${DESKTOP_DISPLAY}" "DBUS_SESSION_BUS_ADDRESS=${DESKTOP_DBUS}")

	# else display is impossible
	else
		# łog problem
		logger "Desktop session data file absent (${DESKTOP_SESSION}). Notification could not be displayed."
	fi
fi

# if some display command has been given
if [ $# -gt 1 ]
then
	# display given command according to environment
	[ ${#ARR_DESKTOP[@]} -gt 0 ] && "${ARR_DESKTOP[@]}" "$@" || "$@"
fi
